package handlers

import (
 "context"
 "crypto/hmac"
 "crypto/rand"
 "crypto/sha256"
 "encoding/base64"
 "encoding/hex"
 "encoding/json"
 "errors"
 "fmt"
 "net/http"
 "net/url"
 "strconv"
 "strings"
 "time"
 "notell/config"
 "notell/models"
 "notell/services"
 "github.com/gin-gonic/gin"
 "golang.org/x/crypto/bcrypt"
 "golang.org/x/oauth2"
 "golang.org/x/oauth2/google"
 "gorm.io/gorm"
)

type AuthHandler struct { DB *gorm.DB; Config *config.Config }
func NewAuthHandler(db *gorm.DB, cfg *config.Config) *AuthHandler { return &AuthHandler{DB: db, Config: cfg} }
const sessionLifetime = 72 * time.Hour
func (h *AuthHandler) setSessionCookie(c *gin.Context, name, value string, maxAge int) { if h.Config.AppEnv == "production" { c.SetSameSite(http.SameSiteNoneMode) } else { c.SetSameSite(http.SameSiteLaxMode) }; domain := ""; if h.Config.AppEnv == "production" && strings.HasSuffix(h.Config.FrontendURL, ".onrender.com") { domain = ".onrender.com" }; c.SetCookie(name, value, maxAge, "/", domain, h.Config.AppEnv == "production", true) }
func (h *AuthHandler) setOAuthStateCookie(c *gin.Context, value string, maxAge int) { if h.Config.AppEnv == "production" { c.SetSameSite(http.SameSiteNoneMode) } else { c.SetSameSite(http.SameSiteLaxMode) }; domain := ""; if h.Config.AppEnv == "production" && strings.HasSuffix(h.Config.FrontendURL, ".onrender.com") { domain = ".onrender.com" }; c.SetCookie("oauth_state", value, maxAge, "/", domain, h.Config.AppEnv == "production", true) }
func (h *AuthHandler) createSession(c *gin.Context, user models.User) error { token, err := services.GenerateToken(user.ID, user.Email, h.Config.JWTSecret); if err != nil { return err }; h.setSessionCookie(c, "auth_token", token, int(sessionLifetime.Seconds())); return nil }
func (h *AuthHandler) clearSession(c *gin.Context) { h.setSessionCookie(c, "auth_token", "", -1) }
type registerInput struct { Username string `json:"username" binding:"required,max=50"`; Email string `json:"email" binding:"required,email,max=254"`; Password string `json:"password" binding:"required,min=6,max=72"`; Country string `json:"country"`; City string `json:"city"`; Bio string `json:"bio"` }
func (h *AuthHandler) Register(c *gin.Context) { var input registerInput; if err := c.ShouldBindJSON(&input); err != nil { c.JSON(400, gin.H{"message": err.Error()}); return }; input.Username = strings.TrimSpace(input.Username); input.Email = strings.ToLower(strings.TrimSpace(input.Email)); input.Country = strings.TrimSpace(input.Country); input.City = strings.TrimSpace(input.City); input.Bio = strings.TrimSpace(input.Bio); if input.Username == "" { c.JSON(400, gin.H{"message": "username cannot be empty"}); return }; if len([]rune(input.Country)) > 100 || len([]rune(input.City)) > 100 || len([]rune(input.Bio)) > 2000 { c.JSON(400, gin.H{"message": "profile field is too long"}); return }; hash, err := bcrypt.GenerateFromPassword([]byte(input.Password), bcrypt.DefaultCost); if err != nil { c.JSON(500, gin.H{"message": "failed hashing password"}); return }; hashString := string(hash); user := models.User{Username: input.Username, Email: input.Email, PasswordHash: &hashString}; if input.Country != "" { user.Country = &input.Country }; if input.City != "" { user.City = &input.City }; if input.Bio != "" { user.Bio = &input.Bio }; if err := h.DB.Create(&user).Error; err != nil { c.JSON(409, gin.H{"message": "username or email already exists"}); return }; if err := h.createSession(c, user); err != nil { c.JSON(500, gin.H{"message": "failed creating session"}); return }; c.JSON(201, gin.H{"message": "registered successfully"}) }
type loginInput struct { Email string `json:"email" binding:"required,email,max=254"`; Password string `json:"password" binding:"required,max=72"` }
func (h *AuthHandler) Login(c *gin.Context) { var input loginInput; if err := c.ShouldBindJSON(&input); err != nil { c.JSON(400, gin.H{"message": err.Error()}); return }; var user models.User; if err := h.DB.Where("email = ?", strings.ToLower(strings.TrimSpace(input.Email))).First(&user).Error; err != nil { c.JSON(401, gin.H{"message": "invalid credentials"}); return }; if user.PasswordHash == nil || bcrypt.CompareHashAndPassword([]byte(*user.PasswordHash), []byte(input.Password)) != nil { c.JSON(401, gin.H{"message": "invalid credentials"}); return }; if err := h.createSession(c, user); err != nil { c.JSON(500, gin.H{"message": "failed creating session"}); return }; c.JSON(200, gin.H{"message": "login successful"}) }
func (h *AuthHandler) Me(c *gin.Context) { userID, exists := c.Get("userId"); if !exists { c.JSON(401, gin.H{"message": "unauthorized"}); return }; var user models.User; err := h.DB.Select("id", "username", "email", "profile_picture", "cover_picture", "bio", "city", "country", "status", "allow_followers", "created_at", "updated_at").First(&user, userID).Error; if err != nil { if errors.Is(err, gorm.ErrRecordNotFound) { c.JSON(401, gin.H{"message": "session user not found"}); return }; c.JSON(500, gin.H{"message": "failed to load current user"}); return }; c.JSON(200, gin.H{"data": gin.H{"user": user}}) }
func (h *AuthHandler) Logout(c *gin.Context) { h.clearSession(c); c.JSON(200, gin.H{"message": "logged out successfully"}) }
func validGiftCode(value string) bool { code := strings.ToUpper(strings.TrimSpace(value)); if len(code) != 6 { return false }; for _, r := range code { if (r < 'A' || r > 'Z') && (r < '0' || r > '9') { return false } }; return true }
func generateOAuthState(secret, mode, giftCode, returnTo string) (string, error) { mode = strings.ToLower(strings.TrimSpace(mode)); if mode != "signup" { mode = "login" }; giftCode = strings.ToUpper(strings.TrimSpace(giftCode)); if !validGiftCode(giftCode) { giftCode = "" }; returnTo = normalizeOAuthReturnTo(returnTo); nonce := make([]byte, 32); if _, err := rand.Read(nonce); err != nil { return "", fmt.Errorf("failed to generate oauth state: %w", err) }; payload := fmt.Sprintf("%d|%s|%s|%s|%s", time.Now().Unix(), mode, giftCode, base64.RawURLEncoding.EncodeToString([]byte(returnTo)), hex.EncodeToString(nonce)); mac := hmac.New(sha256.New, []byte(secret)); _, _ = mac.Write([]byte(payload)); signed := payload + "|" + hex.EncodeToString(mac.Sum(nil)); return base64.RawURLEncoding.EncodeToString([]byte(signed)), nil }
func verifyOAuthState(secret, encoded string) (string, string, string, error) { raw, err := base64.RawURLEncoding.DecodeString(strings.TrimSpace(encoded)); if err != nil { return "", "", "", errors.New("invalid oauth state") }; parts := strings.Split(string(raw), "|"); if len(parts) != 6 { return "", "", "", errors.New("invalid oauth state") }; ts, err := strconv.ParseInt(parts[0], 10, 64); if err != nil { return "", "", "", errors.New("invalid oauth state") }; age := time.Since(time.Unix(ts, 0)); if age < -2*time.Minute || age > 5*time.Minute { return "", "", "", errors.New("oauth state expired") }; mode := strings.ToLower(strings.TrimSpace(parts[1])); if mode != "login" && mode != "signup" { return "", "", "", errors.New("invalid oauth mode") }; giftCode := strings.ToUpper(strings.TrimSpace(parts[2])); if giftCode != "" && !validGiftCode(giftCode) { return "", "", "", errors.New("invalid gift code in oauth state") }; returnToBytes, err := base64.RawURLEncoding.DecodeString(parts[3]); if err != nil { return "", "", "", errors.New("invalid oauth return path") }; returnTo := normalizeOAuthReturnTo(string(returnToBytes)); if returnTo != string(returnToBytes) { return "", "", "", errors.New("invalid oauth return path") }; mac := hmac.New(sha256.New, []byte(secret)); _, _ = mac.Write([]byte(strings.Join(parts[:5], "|"))); expected := hex.EncodeToString(mac.Sum(nil)); if !hmac.Equal([]byte(expected), []byte(parts[5])) { return "", "", "", errors.New("invalid oauth state") }; return mode, giftCode, returnTo, nil }
func normalizeOAuthReturnTo(value string) string { value = strings.TrimSpace(value); if value == "" || value[0] != '/' || strings.HasPrefix(value, "//") || strings.ContainsAny(value, "\r\n") { return "/" }; return value }
func (h *AuthHandler) googleOAuthConfig() *oauth2.Config { return &oauth2.Config{ClientID: h.Config.GoogleClientID, ClientSecret: h.Config.GoogleClientSecret, RedirectURL: h.Config.GoogleRedirectURL, Scopes: []string{"https://www.googleapis.com/auth/userinfo.email", "https://www.googleapis.com/auth/userinfo.profile"}, Endpoint: google.Endpoint} }
func (h *AuthHandler) GoogleLogin(c *gin.Context) { mode := strings.ToLower(strings.TrimSpace(c.Query("mode"))); if mode != "signup" { mode = "login" }; giftCode := c.Query("gift"); if strings.TrimSpace(giftCode) != "" && !validGiftCode(giftCode) { giftCode = "" }; returnTo := normalizeOAuthReturnTo(c.Query("returnTo")); if strings.TrimSpace(h.Config.GoogleClientID) == "" || strings.TrimSpace(h.Config.GoogleClientSecret) == "" || strings.TrimSpace(h.Config.GoogleRedirectURL) == "" || strings.TrimSpace(h.Config.JWTSecret) == "" { c.JSON(http.StatusServiceUnavailable, gin.H{"message": "Google authentication is not configured"}); return }; state, err := generateOAuthState(h.Config.JWTSecret, mode, giftCode, returnTo); if err != nil { c.JSON(500, gin.H{"message": "failed to start Google authentication"}); return }; secure := h.Config.AppEnv == "production"; c.SetSameSite(http.SameSiteLaxMode); h.setOAuthStateCookie(c, state, 5*60); c.Redirect(http.StatusTemporaryRedirect, h.googleOAuthConfig().AuthCodeURL(state, oauth2.AccessTypeOffline, oauth2.SetAuthURLParam("prompt", "select_account"))) }
type GoogleUser struct { ID string `json:"id"`; Email string `json:"email"`; Name string `json:"name"`; Picture string `json:"picture"`; VerifiedEmail bool `json:"verified_email"` }
func (h *AuthHandler) getGoogleUser(ctx context.Context, token *oauth2.Token) (*GoogleUser, error) { client := h.googleOAuthConfig().Client(ctx, token); resp, err := client.Get("https://www.googleapis.com/oauth2/v2/userinfo"); if err != nil { return nil, err }; defer resp.Body.Close(); if resp.StatusCode != 200 { return nil, fmt.Errorf("google userinfo returned status %d", resp.StatusCode) }; var googleUser GoogleUser; if err := json.NewDecoder(resp.Body).Decode(&googleUser); err != nil { return nil, err }; if googleUser.ID == "" || googleUser.Email == "" || !googleUser.VerifiedEmail { return nil, errors.New("google account is missing required verified identity") }; return &googleUser, nil }
func (h *AuthHandler) updateGoogleUser(user *models.User, googleUser *GoogleUser) error { updates := map[string]interface{}{}; if user.GoogleID == nil { updates["google_id"] = googleUser.ID }; if user.ProfilePicture == nil && googleUser.Picture != "" { updates["profile_picture"] = googleUser.Picture }; if len(updates) == 0 { return nil }; return h.DB.Model(user).Updates(updates).Error }
func (h *AuthHandler) findGoogleUser(googleUser *GoogleUser) (*models.User, error) { var user models.User; email := strings.ToLower(strings.TrimSpace(googleUser.Email)); err := h.DB.Where("google_id = ? OR email = ?", googleUser.ID, email).First(&user).Error; if err != nil { return nil, err }; if err := h.updateGoogleUser(&user, googleUser); err != nil { return nil, err }; return &user, nil }
func truncateUsername(value string, maxRunes int) string { runes := []rune(value); if len(runes) <= maxRunes { return value }; return string(runes[:maxRunes]) }
func (h *AuthHandler) createGoogleUser(googleUser *GoogleUser) (*models.User, error) { baseUsername := strings.ToLower(strings.ReplaceAll(strings.TrimSpace(googleUser.Name), " ", "_")); if baseUsername == "" { baseUsername = strings.Split(strings.ToLower(googleUser.Email), "@")[0] }; baseUsername = truncateUsername(baseUsername, 40); if baseUsername == "" { return nil, errors.New("unable to derive Google username") }; profilePicture := googleUser.Picture; for attempt := 0; attempt < 8; attempt++ { username := baseUsername; if attempt > 0 { suffix := fmt.Sprintf("_%d", time.Now().UnixNano()%1000000000); username = truncateUsername(baseUsername, 50-len([]rune(suffix))) + suffix }; user := models.User{Username: username, Email: strings.ToLower(strings.TrimSpace(googleUser.Email)), GoogleID: &googleUser.ID}; if profilePicture != "" { user.ProfilePicture = &profilePicture }; if err := h.DB.Create(&user).Error; err != nil { if !strings.Contains(strings.ToLower(err.Error()), "unique") { return nil, err }; continue }; return &user, nil }; return nil, fmt.Errorf("failed to create Google user after uniqueness conflicts") }
func (h *AuthHandler) GoogleCallback(c *gin.Context) { redirectError := func(code string) { c.Redirect(http.StatusTemporaryRedirect, h.Config.FrontendURL+"/auth?error="+url.QueryEscape(code)) }; state := strings.TrimSpace(c.Query("state")); cookieState, cookieErr := c.Cookie("notell_oauth_state"); c.SetCookie("notell_oauth_state", "", -1, "/", "", h.Config.AppEnv == "production", true); if state == "" || cookieErr != nil || !hmac.Equal([]byte(state), []byte(cookieState)) { redirectError("invalid_state"); return }; if googleErr := strings.TrimSpace(c.Query("error")); googleErr != "" { redirectError("google_"+googleErr); return }; mode, giftCode, returnTo, err := verifyOAuthState(h.Config.JWTSecret, state); if err != nil { redirectError("invalid_state"); return }; code := c.Query("code"); if code == "" { redirectError("no_code"); return }; ctx := c.Request.Context(); oauthToken, err := h.googleOAuthConfig().Exchange(ctx, code); if err != nil { redirectError("exchange_failed"); return }; googleUser, err := h.getGoogleUser(ctx, oauthToken); if err != nil { redirectError("user_fetch_failed"); return }; existingUser, findErr := h.findGoogleUser(googleUser); target := func() string { result := h.Config.FrontendURL + returnTo; if giftCode != "" { separator := "?"; if strings.Contains(result, "?") { separator = "&" }; result += separator + "gift=" + url.QueryEscape(giftCode) }; return result }; if mode == "login" { if findErr != nil { if errors.Is(findErr, gorm.ErrRecordNotFound) { redirectError("google_account_not_registered"); return }; redirectError("google_login_failed"); return }; if err := h.createSession(c, *existingUser); err != nil { redirectError("session_failed"); return }; c.Redirect(http.StatusTemporaryRedirect, target()); return }; if findErr == nil { redirectError("google_account_already_registered"); return }; if !errors.Is(findErr, gorm.ErrRecordNotFound) { redirectError("google_signup_failed"); return }; user, err := h.createGoogleUser(googleUser); if err != nil { redirectError("google_signup_failed"); return }; if err := h.createSession(c, *user); err != nil { redirectError("session_failed"); return }; c.Redirect(http.StatusTemporaryRedirect, target()) }
