import { useEffect, useRef, useState } from "react";
import { Loader2, Mic, MicOff, Radio, Square, Video, VideoOff } from "lucide-react";
import { liveAPI } from "../services/liveApi";
import { getApiErrorMessage } from "../utils/api";

const LIVEKIT_CDN = "https://cdn.jsdelivr.net/npm/livekit-client@2.22.3/dist/livekit-client.umd.min.js";
let sdkPromise;
function loadLiveKit(){
  if(window.LivekitClient) return Promise.resolve(window.LivekitClient);
  if(sdkPromise) return sdkPromise;
  sdkPromise=new Promise((resolve,reject)=>{const script=document.createElement("script");script.src=LIVEKIT_CDN;script.async=true;script.onload=()=>window.LivekitClient?resolve(window.LivekitClient):reject(new Error("LiveKit SDK failed to initialize"));script.onerror=()=>reject(new Error("Unable to load the LiveKit client"));document.head.appendChild(script)});
  return sdkPromise;
}

export default function LiveStreamStudio({channelId}){
  const [stream,setStream]=useState(null); const [title,setTitle]=useState(""); const [description,setDescription]=useState("");
  const [status,setStatus]=useState("idle"); const [error,setError]=useState(""); const [muted,setMuted]=useState(false); const [cameraOff,setCameraOff]=useState(false);
  const videoRef=useRef(null); const roomRef=useRef(null); const localTracksRef=useRef([]); const sdkRef=useRef(null);
  const cleanup=()=>{localTracksRef.current.forEach((track)=>{try{track.stop()}catch{}});localTracksRef.current=[];if(roomRef.current){roomRef.current.disconnect();roomRef.current=null}if(videoRef.current)videoRef.current.srcObject=null};
  useEffect(()=>()=>cleanup(),[]);
  const create=async()=>{setError("");setStatus("creating");try{const result=await liveAPI.create(channelId,{title:title.trim()||"Live stream",description:description.trim()});setStream(result.stream||result?.data?.stream);setTitle(result.stream?.title||"Live stream");setDescription(result.stream?.description||"");setStatus("draft")}catch(e){setError(getApiErrorMessage(e,"Unable to create the live stream."));setStatus("idle")}};
  const start=async()=>{setError("");setStatus("starting");try{const [sdk,result]=await Promise.all([loadLiveKit(),liveAPI.start(stream.id)]);if(!result?.hostToken||!result?.livekitUrl)throw new Error("Live transport is not configured");sdkRef.current=sdk;const room=new sdk.Room({adaptiveStream:true,dynacast:true});roomRef.current=room;room.on(sdk.RoomEvent.LocalTrackPublished,(publication)=>{const track=publication.track;if(track&&!localTracksRef.current.includes(track))localTracksRef.current.push(track)});await room.connect(result.livekitUrl,result.hostToken,{autoSubscribe:true});const tracks=await sdk.createLocalTracks({audio:true,video:true});for(const track of tracks){await room.localParticipant.publishTrack(track);localTracksRef.current.push(track);if(track.kind===sdk.Track.Kind.Video)track.attach(videoRef.current)}setStatus("live")}catch(e){cleanup();setError(getApiErrorMessage(e,"Unable to start the live stream."));setStatus("draft")}};
  const end=async()=>{if(!stream)return;setError("");setStatus("ending");try{await liveAPI.end(stream.id);cleanup();setStatus("ended");setStream((current)=>current?{...current,status:"ended"}:current)}catch(e){setError(getApiErrorMessage(e,"Unable to end the live stream."));setStatus("live")}};
  const toggleMute=()=>{const sdk=sdkRef.current;const room=roomRef.current;if(!sdk||!room)return;room.localParticipant.audioTrackPublications.forEach((publication)=>publication.track?.enable(muted));setMuted((value)=>!value)};
  const toggleCamera=()=>{const sdk=sdkRef.current;const room=roomRef.current;if(!sdk||!room)return;room.localParticipant.videoTrackPublications.forEach((publication)=>publication.track?.enable(cameraOff));setCameraOff((value)=>!value)};
  return <section className="mt-6 overflow-hidden rounded-3xl border border-neutral-800 bg-neutral-900/60"><div className="border-b border-neutral-800 px-5 py-4"><div className="flex items-center gap-2"><Radio size={17}/><h2 className="font-black">Live studio</h2>{status==="live"&&<span className="ml-auto rounded-full bg-red-500 px-2 py-1 text-[9px] font-black text-white">LIVE</span>}</div><p className="mt-1 text-xs text-neutral-500">Start a browser-based live broadcast with your camera and microphone.</p></div><div className="p-5"><div className="relative aspect-video overflow-hidden rounded-2xl bg-black"><video ref={videoRef} autoPlay muted playsInline className="h-full w-full object-contain" />{status!=="live"&&<div className="absolute inset-0 flex items-center justify-center text-xs text-neutral-600">{status==="creating"||status==="starting"?<Loader2 className="animate-spin"/>:status==="ended"?"Stream ended":"Camera preview appears when you go live"}</div>}{status==="live"&&<div className="absolute bottom-3 left-3 right-3 flex justify-center gap-2"><button type="button" onClick={toggleMute} className="rounded-full bg-black/70 p-2 text-white" aria-label={muted?"Unmute microphone":"Mute microphone"}>{muted?<MicOff size={16}/>:<Mic size={16}/>}</button><button type="button" onClick={toggleCamera} className="rounded-full bg-black/70 p-2 text-white" aria-label={cameraOff?"Enable camera":"Disable camera"}>{cameraOff?<VideoOff size={16}/>:<Video size={16}/>}</button><button type="button" onClick={end} className="rounded-full bg-red-600 px-4 py-2 text-[10px] font-black text-white"><Square size={14} className="inline mr-1"/>End live</button></div>}</div>{(status==="idle"||status==="draft")&&<div className="mt-4 grid gap-3"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Live title" className="rounded-xl border border-neutral-800 bg-neutral-950 px-4 py-3 text-sm outline-none"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe what you are streaming" className="min-h-20 rounded-xl border border-neutral-800 bg-neutral-950 px-4 py-3 text-sm outline-none"/><div className="flex justify-end">{status==="idle"?<button type="button" onClick={create} className="rounded-xl bg-neutral-100 px-4 py-3 text-xs font-black text-neutral-950">Create live stream</button>:<button type="button" onClick={start} className="rounded-xl bg-neutral-100 px-4 py-3 text-xs font-black text-neutral-950">Go live</button>}</div></div>}{error&&<p className="mt-3 text-xs text-red-300">{error}</p>}</div></section>;
}
