package main

import (
 "fmt"
 "time"
 "github.com/gin-gonic/gin"
 "gorm.io/gorm"
)

type ChannelTeamMember struct { ID uint64 `gorm:"primaryKey" json:"id"`; ChannelID uint64 `gorm:"not null;uniqueIndex:idx_team_member" json:"channelId"`; UserID uint64 `gorm:"not null;uniqueIndex:idx_team_member;index" json:"userId"`; Role Role `gorm:"size:24;not null;index" json:"role"`; Status string `gorm:"size:16;not null;default:ACTIVE;index" json:"status"`; CreatedAt time.Time `json:"createdAt"`; UpdatedAt time.Time `json:"updatedAt"` }
type ChannelInvitation struct { ID uint64 `gorm:"primaryKey" json:"id"`; ChannelID uint64 `gorm:"not null;index" json:"channelId"`; InviterUserID uint64 `gorm:"not null;index" json:"inviterUserId"`; InvitedUserID uint64 `gorm:"not null;index" json:"invitedUserId"`; Role Role `gorm:"size:24;not null" json:"role"`; Status string `gorm:"size:16;not null;default:PENDING;index" json:"status"`; ExpiresAt time.Time `gorm:"not null;index" json:"expiresAt"`; AcceptedAt *time.Time `json:"acceptedAt,omitempty"`; CreatedAt time.Time `json:"createdAt"`; UpdatedAt time.Time `json:"updatedAt"` }

var rolePermissions = map[Role]map[string]bool{RoleOwner:{"team":true,"channel":true,"content":true,"schedule":true,"live":true,"moderate":true,"analytics":true},RoleAdmin:{"team":true,"channel":true,"content":true,"schedule":true,"live":true,"moderate":true,"analytics":true},RoleEditor:{"content":true,"schedule":true,"analytics":true},RoleBroadcaster:{"live":true,"schedule":true,"analytics":true},RoleModerator:{"moderate":true,"analytics":true},RoleAnalyst:{"analytics":true}}
func channelID(c *gin.Context) uint64 { var id uint64; _,_ = fmt.Sscan(c.Param("id"),&id); return id }
func hasPermission(db *gorm.DB,c *gin.Context,id uint64,p string) bool { uid:=userID(c); var ch Channel; if db.First(&ch,id).Error==nil && ch.OwnerID==uid{return true}; var m ChannelTeamMember; if db.Where("channel_id=? AND user_id=? AND status=?",id,uid,"ACTIVE").First(&m).Error!=nil || !rolePermissions[m.Role][p] { c.JSON(403,gin.H{"message":"insufficient channel permission"}); return false }; return true }
func validRole(r Role) bool { return r==RoleAdmin||r==RoleEditor||r==RoleBroadcaster||r==RoleModerator||r==RoleAnalyst }
func listTeam(db *gorm.DB) gin.HandlerFunc{return func(c *gin.Context){id:=channelID(c);if !hasPermission(db,c,id,"team"){return};var rows []ChannelTeamMember;if err:=db.Where("channel_id=? AND status=?",id,"ACTIVE").Order("created_at ASC").Find(&rows).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to list team"});return};c.JSON(200,gin.H{"team":rows})}}
func inviteTeam(db *gorm.DB) gin.HandlerFunc{return func(c *gin.Context){id:=channelID(c);if !hasPermission(db,c,id,"team"){return};var in struct{UserID uint64 `json:"userId"`;Role Role `json:"role"`};if c.ShouldBindJSON(&in)!=nil||in.UserID==0||!validRole(in.Role){c.JSON(400,gin.H{"message":"userId and valid role are required"});return};var count int64;db.Model(&ChannelTeamMember{}).Where("channel_id=? AND status=?",id,"ACTIVE").Count(&count);var ent ChannelEntitlement;if db.Where("channel_id=?",id).First(&ent).Error==nil{var plan ChannelPlan;if db.Where("code=?",ent.PlanCode).First(&plan).Error==nil&&int(count)>=plan.ManagerLimit{c.JSON(409,gin.H{"message":"channel manager limit reached"});return}};row:=ChannelInvitation{ChannelID:id,InviterUserID:userID(c),InvitedUserID:in.UserID,Role:in.Role,Status:"PENDING",ExpiresAt:time.Now().UTC().Add(7*24*time.Hour)};if err:=db.Create(&row).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to create invitation"});return};c.JSON(201,row)}}
func acceptTeamInvite(db *gorm.DB) gin.HandlerFunc{return func(c *gin.Context){id:=channelID(c);var iid uint64;_,_=fmt.Sscan(c.Param("invitationId"),&iid);var inv ChannelInvitation;if db.First(&inv,iid).Error!=nil||inv.ChannelID!=id||inv.InvitedUserID!=userID(c){c.JSON(404,gin.H{"message":"invitation not found"});return};if inv.Status!="PENDING"||time.Now().UTC().After(inv.ExpiresAt){c.JSON(409,gin.H{"message":"invitation is no longer valid"});return};m:=ChannelTeamMember{ChannelID:id,UserID:userID(c),Role:inv.Role,Status:"ACTIVE"};err:=db.Transaction(func(tx *gorm.DB)error{if err:=tx.Create(&m).Error;err!=nil{return err};now:=time.Now().UTC();return tx.Model(&inv).Updates(map[string]any{"status":"ACCEPTED","accepted_at":now}).Error});if err!=nil{c.JSON(500,gin.H{"message":"failed to accept invitation"});return};c.JSON(200,m)}}
func updateTeam(db *gorm.DB) gin.HandlerFunc{return func(c *gin.Context){id:=channelID(c);if !hasPermission(db,c,id,"team"){return};var uid uint64;_,_=fmt.Sscan(c.Param("userId"),&uid);var in struct{Role Role `json:"role"`};if c.ShouldBindJSON(&in)!=nil||!validRole(in.Role){c.JSON(400,gin.H{"message":"valid role is required"});return};var m ChannelTeamMember;if db.Where("channel_id=? AND user_id=?",id,uid).First(&m).Error!=nil{c.JSON(404,gin.H{"message":"team member not found"});return};m.Role=in.Role;if err:=db.Save(&m).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to update team member"});return};c.JSON(200,m)}}
func removeTeam(db *gorm.DB) gin.HandlerFunc{return func(c *gin.Context){id:=channelID(c);if !hasPermission(db,c,id,"team"){return};var uid uint64;_,_=fmt.Sscan(c.Param("userId"),&uid);if err:=db.Model(&ChannelTeamMember{}).Where("channel_id=? AND user_id=?",id,uid).Update("status","REMOVED").Error;err!=nil{c.JSON(500,gin.H{"message":"failed to remove team member"});return};c.Status(204)}}
