package main

import (
 "fmt"
 "strings"
 "time"
 "github.com/gin-gonic/gin"
 "gorm.io/gorm"
)

type ChannelProgram struct { ID uint64 `gorm:"primaryKey" json:"id"`; ChannelID uint64 `gorm:"not null;index" json:"channelId"`; Title string `gorm:"size:160;not null" json:"title"`; Description string `gorm:"type:text" json:"description,omitempty"`; Status string `gorm:"size:16;not null;default:DRAFT;index" json:"status"`; CreatedBy uint64 `gorm:"not null;index" json:"createdBy"`; CreatedAt time.Time `json:"createdAt"`; UpdatedAt time.Time `json:"updatedAt"` }
type ChannelSchedule struct { ID uint64 `gorm:"primaryKey" json:"id"`; ChannelID uint64 `gorm:"not null;index" json:"channelId"`; ProgramID *uint64 `gorm:"index" json:"programId,omitempty"`; Title string `gorm:"size:160;not null" json:"title"`; StartsAt time.Time `gorm:"not null;index" json:"startsAt"`; EndsAt *time.Time `json:"endsAt,omitempty"`; Status string `gorm:"size:16;not null;default:SCHEDULED;index" json:"status"`; CreatedBy uint64 `gorm:"not null;index" json:"createdBy"`; CreatedAt time.Time `json:"createdAt"`; UpdatedAt time.Time `json:"updatedAt"` }
type ChannelContent struct { ID uint64 `gorm:"primaryKey" json:"id"`; ChannelID uint64 `gorm:"not null;index" json:"channelId"`; PostID uint64 `gorm:"not null;uniqueIndex:idx_channel_post" json:"postId"`; Status string `gorm:"size:16;not null;default:PUBLISHED;index" json:"status"`; CreatedBy uint64 `gorm:"not null;index" json:"createdBy"`; CreatedAt time.Time `json:"createdAt"`; UpdatedAt time.Time `json:"updatedAt"` }
type ChannelSetting struct { ID uint64 `gorm:"primaryKey" json:"id"`; ChannelID uint64 `gorm:"not null;uniqueIndex:idx_channel_setting" json:"channelId"`; Key string `gorm:"size:80;not null;uniqueIndex:idx_channel_setting" json:"key"`; Value string `gorm:"type:text;not null" json:"value"`; UpdatedBy uint64 `gorm:"not null" json:"updatedBy"`; CreatedAt time.Time `json:"createdAt"`; UpdatedAt time.Time `json:"updatedAt"` }
func programs(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var rows []ChannelProgram;if err:=db.Where("channel_id=?",channelID(c)).Order("created_at DESC").Find(&rows).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to list programs"});return};c.JSON(200,gin.H{"programs":rows})}}
func publicPrograms(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var rows []ChannelProgram;if err:=db.Where("channel_id=? AND status=?",channelID(c),"PUBLISHED").Order("created_at DESC").Limit(50).Find(&rows).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to list programs"});return};c.JSON(200,gin.H{"programs":rows})}}
func publicContent(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var rows []ChannelContent;if err:=db.Where("channel_id=? AND status=?",channelID(c),"PUBLISHED").Order("created_at DESC").Limit(50).Find(&rows).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to list content"});return};c.JSON(200,gin.H{"content":rows})}}
func publicSchedule(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var rows []ChannelSchedule;q:=db.Where("channel_id=? AND status=?",channelID(c),"SCHEDULED");if err:=q.Order("starts_at ASC").Limit(50).Find(&rows).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to list schedule"});return};c.JSON(200,gin.H{"schedule":rows})}}
func createProgram(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){id:=channelID(c);if !hasPermission(db,c,id,"schedule"){return};var in struct{Title,Description,Status string};if c.ShouldBindJSON(&in)!=nil||strings.TrimSpace(in.Title)==""{c.JSON(400,gin.H{"message":"title is required"});return};st:=strings.ToUpper(strings.TrimSpace(in.Status));if st==""{st="DRAFT"};if st!="DRAFT"&&st!="PUBLISHED"&&st!="ARCHIVED"{c.JSON(400,gin.H{"message":"invalid status"});return};row:=ChannelProgram{ChannelID:id,Title:strings.TrimSpace(in.Title),Description:strings.TrimSpace(in.Description),Status:st,CreatedBy:userID(c)};if err:=db.Create(&row).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to create program"});return};c.JSON(201,row)}}
func updateProgram(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){id:=channelID(c);if !hasPermission(db,c,id,"schedule"){return};var pid uint64;_,_=fmt.Sscan(c.Param("programId"),&pid);var row ChannelProgram;if db.Where("id=? AND channel_id=?",pid,id).First(&row).Error!=nil{c.JSON(404,gin.H{"message":"program not found"});return};var in struct{Title,Description,Status string};if c.ShouldBindJSON(&in)!=nil{c.JSON(400,gin.H{"message":"invalid request body"});return};if strings.TrimSpace(in.Title)!=""{row.Title=strings.TrimSpace(in.Title)};if in.Description!=""{row.Description=strings.TrimSpace(in.Description)};if in.Status!=""{row.Status=strings.ToUpper(strings.TrimSpace(in.Status))};if err:=db.Save(&row).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to update program"});return};c.JSON(200,row)}}
func deleteProgram(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){id:=channelID(c);if !hasPermission(db,c,id,"schedule"){return};var pid uint64;_,_=fmt.Sscan(c.Param("programId"),&pid);if err:=db.Where("id=? AND channel_id=?",pid,id).Delete(&ChannelProgram{}).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to delete program"});return};c.Status(204)}}
func schedules(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var rows []ChannelSchedule;q:=db.Where("channel_id=?",channelID(c));if v:=c.Query("from");v!=""{if t,e:=time.Parse(time.RFC3339,v);e==nil{q=q.Where("starts_at>=?",t)}};if v:=c.Query("to");v!=""{if t,e:=time.Parse(time.RFC3339,v);e==nil{q=q.Where("starts_at<=?",t)}};if err:=q.Order("starts_at ASC").Find(&rows).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to list schedule"});return};c.JSON(200,gin.H{"schedule":rows})}}
func createSchedule(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){id:=channelID(c);if !hasPermission(db,c,id,"schedule"){return};var in struct{ProgramID *uint64 `json:"programId"`;Title string `json:"title"`;StartsAt time.Time `json:"startsAt"`;EndsAt *time.Time `json:"endsAt"`;Status string `json:"status"`};if c.ShouldBindJSON(&in)!=nil||strings.TrimSpace(in.Title)==""||in.StartsAt.IsZero(){c.JSON(400,gin.H{"message":"title and startsAt are required"});return};st:=strings.ToUpper(strings.TrimSpace(in.Status));if st==""{st="SCHEDULED"};row:=ChannelSchedule{ChannelID:id,ProgramID:in.ProgramID,Title:strings.TrimSpace(in.Title),StartsAt:in.StartsAt,EndsAt:in.EndsAt,Status:st,CreatedBy:userID(c)};if err:=db.Create(&row).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to create schedule"});return};c.JSON(201,row)}}
func content(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var rows []ChannelContent;if err:=db.Where("channel_id=?",channelID(c)).Order("created_at DESC").Find(&rows).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to list content"});return};c.JSON(200,gin.H{"content":rows})}}
func linkContent(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){id:=channelID(c);if !hasPermission(db,c,id,"content"){return};var in struct{PostID uint64 `json:"postId"`;Status string `json:"status"`};if c.ShouldBindJSON(&in)!=nil||in.PostID==0{c.JSON(400,gin.H{"message":"postId is required"});return};st:=strings.ToUpper(strings.TrimSpace(in.Status));if st==""{st="PUBLISHED"};row:=ChannelContent{ChannelID:id,PostID:in.PostID,Status:st,CreatedBy:userID(c)};if err:=db.Create(&row).Error;err!=nil{c.JSON(409,gin.H{"message":"post is already linked or invalid"});return};c.JSON(201,row)}}
func unlinkContent(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){id:=channelID(c);if !hasPermission(db,c,id,"content"){return};var cid uint64;_,_=fmt.Sscan(c.Param("contentId"),&cid);if err:=db.Where("id=? AND channel_id=?",cid,id).Delete(&ChannelContent{}).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to unlink content"});return};c.Status(204)}}
func audience(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){id:=channelID(c);if !hasPermission(db,c,id,"analytics"){return};var followers,subs,team int64;db.Model(&ChannelMember{}).Where("channel_id=? AND membership_type=? AND status=?",id,MembershipFollower,"ACTIVE").Count(&followers);db.Model(&ChannelMember{}).Where("channel_id=? AND membership_type=? AND status=?",id,MembershipSubscriber,"ACTIVE").Count(&subs);db.Model(&ChannelTeamMember{}).Where("channel_id=? AND status=?",id,"ACTIVE").Count(&team);c.JSON(200,gin.H{"followers":followers,"subscribers":subs,"teamMembers":team})}}
func studioSettings(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){id:=channelID(c);if !hasPermission(db,c,id,"channel"){return};var rows []ChannelSetting;if err:=db.Where("channel_id=?",id).Order("key ASC").Find(&rows).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to load settings"});return};c.JSON(200,gin.H{"settings":rows})}}
func setStudioSetting(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){id:=channelID(c);if !hasPermission(db,c,id,"channel"){return};key:=strings.TrimSpace(c.Param("key"));var in struct{Value string `json:"value"`};if key==""||len(key)>80||c.ShouldBindJSON(&in)!=nil{c.JSON(400,gin.H{"message":"valid key and value are required"});return};var row ChannelSetting;err:=db.Where("channel_id=? AND key=?",id,key).First(&row).Error;if err==gorm.ErrRecordNotFound{row=ChannelSetting{ChannelID:id,Key:key,Value:in.Value,UpdatedBy:userID(c)};err=db.Create(&row).Error}else if err==nil{row.Value=in.Value;row.UpdatedBy=userID(c);err=db.Save(&row).Error};if err!=nil{c.JSON(500,gin.H{"message":"failed to save setting"});return};c.JSON(200,row)}}
