package main

import (
 "errors"
 "strings"
 "time"
 "github.com/gin-gonic/gin"
 "gorm.io/gorm"
)

type LiveState string
const(LiveScheduled LiveState="SCHEDULED";LiveLive LiveState="LIVE";LiveEnded LiveState="ENDED";LiveCancelled LiveState="CANCELLED")
type LiveSession struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;index" json:"channelId"`;OwnerID uint64 `gorm:"not null;index" json:"ownerId"`;Title string `gorm:"size:160;not null" json:"title"`;State LiveState `gorm:"size:16;not null;index" json:"state"`;IngestKeyHash string `gorm:"size:128" json:"-"`;PlaybackRef string `gorm:"size:512" json:"playbackRef,omitempty"`;StartedAt *time.Time `json:"startedAt,omitempty"`;EndedAt *time.Time `json:"endedAt,omitempty"`;CreatedAt time.Time `json:"createdAt"`;UpdatedAt time.Time `json:"updatedAt"`}
type MediaReference struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;index" json:"channelId"`;OwnerID uint64 `gorm:"not null;index" json:"ownerId"`;MediaID string `gorm:"size:160;not null;index" json:"mediaId"`;Access string `gorm:"size:16;not null" json:"access"`;Status string `gorm:"size:16;not null;index" json:"status"`;CreatedAt time.Time `json:"createdAt"`}

type SafetyCase struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;index" json:"channelId"`;ReporterID uint64 `gorm:"not null;index" json:"reporterId"`;TargetType string `gorm:"size:32;not null" json:"targetType"`;TargetID string `gorm:"size:160;not null" json:"targetId"`;Reason string `gorm:"size:80;not null" json:"reason"`;Status string `gorm:"size:24;not null;index" json:"status"`;Notes string `gorm:"type:text" json:"notes,omitempty"`;CreatedAt time.Time `json:"createdAt"`;UpdatedAt time.Time `json:"updatedAt"`}
type RightsRecord struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;index" json:"channelId"`;MediaID string `gorm:"size:160;not null;index" json:"mediaId"`;RightsType string `gorm:"size:40;not null" json:"rightsType"`;LicenseRef string `gorm:"size:256" json:"licenseRef,omitempty"`;Status string `gorm:"size:24;not null;index" json:"status"`;CreatedAt time.Time `json:"createdAt"`;UpdatedAt time.Time `json:"updatedAt"`}

type MonetizationEligibility struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;uniqueIndex" json:"channelId"`;Eligible bool `gorm:"not null;default:false" json:"eligible"`;Reason string `gorm:"size:256" json:"reason,omitempty"`;CheckedAt time.Time `json:"checkedAt"`}
type RevenueEvent struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;index" json:"channelId"`;UserID uint64 `gorm:"index" json:"userId,omitempty"`;EventType string `gorm:"size:48;not null;index" json:"eventType"`;ReferenceID string `gorm:"size:160;index" json:"referenceId,omitempty"`;GrossCents int64 `gorm:"not null" json:"grossCents"`;PlatformFeeCents int64 `gorm:"not null" json:"platformFeeCents"`;CreatorCents int64 `gorm:"not null" json:"creatorCents"`;Currency string `gorm:"size:8;not null;default:USD" json:"currency"`;Status string `gorm:"size:24;not null;index" json:"status"`;CreatedAt time.Time `json:"createdAt"`}
type AdCampaign struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;index" json:"channelId"`;OwnerID uint64 `gorm:"not null;index" json:"ownerId"`;Name string `gorm:"size:160;not null" json:"name"`;Status string `gorm:"size:24;not null;index" json:"status"`;BudgetCents int64 `gorm:"not null" json:"budgetCents"`;CreatedAt time.Time `json:"createdAt"`;UpdatedAt time.Time `json:"updatedAt"`}
type ChannelMetric struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;index" json:"channelId"`;Metric string `gorm:"size:64;not null;index" json:"metric"`;Value int64 `gorm:"not null" json:"value"`;PeriodStart time.Time `gorm:"not null;index" json:"periodStart"`;PeriodEnd time.Time `gorm:"not null;index" json:"periodEnd"`}

type liveInput struct{Title string `json:"title"`;PlaybackRef string `json:"playbackRef"`}
func channelOwner(db *gorm.DB,c *gin.Context)(Channel,bool){var ch Channel;if db.First(&ch,c.Param("id")).Error!=nil||ch.Status==ChannelDisabled{c.JSON(404,gin.H{"message":"channel not found"});return ch,false};if ch.OwnerID!=userID(c){c.JSON(403,gin.H{"message":"channel owner required"});return ch,false};return ch,true}
func registerC6C8(db *gorm.DB,p *gin.RouterGroup){
 p.GET("/channels/:id/live",listLive(db));p.POST("/channels/:id/live",createLive(db));p.PATCH("/channels/:id/live/:sessionId",updateLive(db));p.POST("/channels/:id/live/:sessionId/start",startLive(db));p.POST("/channels/:id/live/:sessionId/end",endLive(db));p.DELETE("/channels/:id/live/:sessionId",cancelLive(db));
 p.GET("/channels/:id/media",listMediaRefs(db));p.POST("/channels/:id/media",addMediaRef(db));p.DELETE("/channels/:id/media/:mediaId",removeMediaRef(db));p.GET("/channels/:id/playback/:mediaId",playbackAuthorization(db));
 p.POST("/channels/:id/reports",reportCase(db));p.GET("/channels/:id/safety/cases",listCases(db));p.PATCH("/channels/:id/safety/cases/:caseId",updateCase(db));p.POST("/channels/:id/rights",setRights(db));p.GET("/channels/:id/rights",listRights(db));
 p.GET("/channels/:id/monetization",getEligibility(db));p.PUT("/channels/:id/monetization",setEligibility(db));p.POST("/channels/:id/revenue",recordRevenue(db));p.GET("/channels/:id/revenue",listRevenue(db));p.POST("/channels/:id/ads",createAd(db));p.GET("/channels/:id/ads",listAds(db));p.GET("/channels/:id/analytics",analytics(db))
}
func listLive(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x []LiveSession;db.Where("channel_id=?",c.Param("id")).Order("created_at DESC").Limit(100).Find(&x);c.JSON(200,gin.H{"sessions":x})}}
func createLive(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var in liveInput;if c.ShouldBindJSON(&in)!=nil||strings.TrimSpace(in.Title)==""{c.JSON(400,gin.H{"message":"title is required"});return};x:=LiveSession{ChannelID:ch.ID,OwnerID:ch.OwnerID,Title:strings.TrimSpace(in.Title),State:LiveScheduled,PlaybackRef:strings.TrimSpace(in.PlaybackRef)};if err:=db.Create(&x).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to create live session"});return};c.JSON(201,x)}}
func updateLive(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var x LiveSession;if db.Where("id=? AND channel_id=?",c.Param("sessionId"),ch.ID).First(&x).Error!=nil{c.JSON(404,gin.H{"message":"live session not found"});return};var in liveInput;if c.ShouldBindJSON(&in)!=nil{c.JSON(400,gin.H{"message":"invalid request"});return};if x.State==LiveLive||x.State==LiveEnded{c.JSON(409,gin.H{"message":"live session is no longer editable"});return};if strings.TrimSpace(in.Title)!=""{x.Title=strings.TrimSpace(in.Title)};if in.PlaybackRef!=""{x.PlaybackRef=strings.TrimSpace(in.PlaybackRef)};db.Save(&x);c.JSON(200,x)}}
func startLive(db *gorm.DB)gin.HandlerFunc{return transitionLive(db,c,LiveLive)}
func endLive(db *gorm.DB)gin.HandlerFunc{return transitionLive(db,c,LiveEnded)}
func transitionLive(db *gorm.DB,c *gin.Context,state LiveState)error{return nil}
func cancelLive(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var x LiveSession;if db.Where("id=? AND channel_id=?",c.Param("sessionId"),ch.ID).First(&x).Error!=nil{c.JSON(404,gin.H{"message":"live session not found"});return};if x.State==LiveLive{c.JSON(409,gin.H{"message":"live session must be ended before cancellation"});return};x.State=LiveCancelled;db.Save(&x);c.Status(204)}}
func listMediaRefs(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x []MediaReference;db.Where("channel_id=? AND status=?",c.Param("id"),"ACTIVE").Order("created_at DESC").Limit(100).Find(&x);c.JSON(200,gin.H{"media":x})}}
type mediaInput struct{MediaID string `json:"mediaId"`;Access string `json:"access"`}
func addMediaRef(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var in mediaInput;if c.ShouldBindJSON(&in)!=nil||strings.TrimSpace(in.MediaID)==""{c.JSON(400,gin.H{"message":"mediaId is required"});return};if in.Access!="PRIVATE"{in.Access="PUBLIC"};x:=MediaReference{ChannelID:ch.ID,OwnerID:ch.OwnerID,MediaID:strings.TrimSpace(in.MediaID),Access:in.Access,Status:"ACTIVE"};if err:=db.Create(&x).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to link media"});return};c.JSON(201,x)}}
func removeMediaRef(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};if err:=db.Model(&MediaReference{}).Where("channel_id=? AND media_id=?",ch.ID,c.Param("mediaId")).Update("status","REMOVED").Error;err!=nil{c.JSON(500,gin.H{"message":"failed to unlink media"});return};c.Status(204)}}
func playbackAuthorization(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x MediaReference;if db.Where("channel_id=? AND media_id=? AND status=?",c.Param("id"),c.Param("mediaId"),"ACTIVE").First(&x).Error!=nil{c.JSON(404,gin.H{"message":"media not found"});return};if x.Access=="PRIVATE"{c.JSON(200,gin.H{"allowed":false,"reason":"subscriber_entitlement_required","mediaId":x.MediaID});return};c.JSON(200,gin.H{"allowed":true,"mediaId":x.MediaID,"access":"PUBLIC"})}}
func reportCase(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var in struct{TargetType,TargetID,Reason,Notes string `json:"-"`};if c.ShouldBindJSON(&in)!=nil{c.JSON(400,gin.H{"message":"invalid request"});return};var raw map[string]any;c.ShouldBindJSON(&raw);x:=SafetyCase{ChannelID:mustID(c.Param("id")),ReporterID:userID(c),TargetType:stringValue(raw,"targetType"),TargetID:stringValue(raw,"targetId"),Reason:stringValue(raw,"reason"),Notes:stringValue(raw,"notes"),Status:"OPEN"};if x.TargetType==""||x.TargetID==""||x.Reason==""{c.JSON(400,gin.H{"message":"targetType, targetId and reason are required"});return};db.Create(&x);c.JSON(201,x)}}
func listCases(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x []SafetyCase;db.Where("channel_id=?",c.Param("id")).Order("created_at DESC").Limit(100).Find(&x);c.JSON(200,gin.H{"cases":x})}}
func updateCase(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x SafetyCase;if db.Where("id=? AND channel_id=?",c.Param("caseId"),c.Param("id")).First(&x).Error!=nil{c.JSON(404,gin.H{"message":"case not found"});return};var in struct{Status string `json:"status"`;Notes string `json:"notes"`};if c.ShouldBindJSON(&in)!=nil{c.JSON(400,gin.H{"message":"invalid request"});return};if in.Status!="OPEN"&&in.Status!="REVIEWING"&&in.Status!="RESOLVED"&&in.Status!="REJECTED"{c.JSON(400,gin.H{"message":"invalid status"});return};x.Status=in.Status;x.Notes=in.Notes;db.Save(&x);c.JSON(200,x)}}
func setRights(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var in struct{MediaID,RightsType,LicenseRef string `json:"-"`};var raw map[string]any;if c.ShouldBindJSON(&raw)!=nil{c.JSON(400,gin.H{"message":"invalid request"});return};x:=RightsRecord{ChannelID:ch.ID,MediaID:stringValue(raw,"mediaId"),RightsType:stringValue(raw,"rightsType"),LicenseRef:stringValue(raw,"licenseRef"),Status:"ACTIVE"};if x.MediaID==""||x.RightsType==""{c.JSON(400,gin.H{"message":"mediaId and rightsType are required"});return};db.Create(&x);c.JSON(201,x)}}
func listRights(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x []RightsRecord;db.Where("channel_id=?",c.Param("id")).Order("created_at DESC").Find(&x);c.JSON(200,gin.H{"rights":x})}}
func getEligibility(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x MonetizationEligibility;if err:=db.Where("channel_id=?",c.Param("id")).First(&x).Error;err!=nil{c.JSON(200,gin.H{"eligible":false,"reason":"not_reviewed"});return};c.JSON(200,x)}}
func setEligibility(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var in struct{Eligible bool `json:"eligible"`;Reason string `json:"reason"`};if c.ShouldBindJSON(&in)!=nil{c.JSON(400,gin.H{"message":"invalid request"});return};x:=MonetizationEligibility{ChannelID:ch.ID,Eligible:in.Eligible,Reason:strings.TrimSpace(in.Reason),CheckedAt:time.Now()};db.Where("channel_id=?",ch.ID).Assign(x).FirstOrCreate(&x);c.JSON(200,x)}}
type revenueInput struct{UserID uint64 `json:"userId"`;EventType,ReferenceID,Currency string `json:"-"`;GrossCents int64 `json:"grossCents"`}
func recordRevenue(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var raw map[string]any;if c.ShouldBindJSON(&raw)!=nil{c.JSON(400,gin.H{"message":"invalid request"});return};gross:=int64Value(raw,"grossCents");if gross<0{c.JSON(400,gin.H{"message":"grossCents must be non-negative"});return};fee:=gross/5;x:=RevenueEvent{ChannelID:ch.ID,UserID:uint64(int64Value(raw,"userId")),EventType:stringValue(raw,"eventType"),ReferenceID:stringValue(raw,"referenceId"),GrossCents:gross,PlatformFeeCents:fee,CreatorCents:gross-fee,Currency:stringValue(raw,"currency"),Status:"PENDING"};if x.Currency==""{x.Currency="USD"};if x.EventType==""{c.JSON(400,gin.H{"message":"eventType is required"});return};db.Create(&x);c.JSON(201,x)}}
func listRevenue(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x []RevenueEvent;db.Where("channel_id=?",c.Param("id")).Order("created_at DESC").Limit(100).Find(&x);c.JSON(200,gin.H{"events":x})}}
func createAd(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var x AdCampaign;if c.ShouldBindJSON(&x)!=nil{c.JSON(400,gin.H{"message":"invalid request"});return};x.ID=0;x.ChannelID=ch.ID;x.OwnerID=ch.OwnerID;if x.Status==""{x.Status="DRAFT"};db.Create(&x);c.JSON(201,x)}}
func listAds(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x []AdCampaign;db.Where("channel_id=?",c.Param("id")).Order("created_at DESC").Find(&x);c.JSON(200,gin.H{"ads":x})}}
func analytics(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x []ChannelMetric;db.Where("channel_id=?",c.Param("id")).Order("period_end DESC").Limit(200).Find(&x);c.JSON(200,gin.H{"metrics":x})}}
func mustID(s string)uint64{var n uint64;for _,r:=range s{if r<'0'||r>'9'{return 0};n=n*10+uint64(r-'0')};return n}
func stringValue(m map[string]any,k string)string{if v,ok:=m[k].(string);ok{return strings.TrimSpace(v)};return ""}
func int64Value(m map[string]any,k string)int64{if v,ok:=m[k].(float64);ok{return int64(v)};return 0}
var _=errors.Is
