package main

import("strings";"time";"github.com/gin-gonic/gin";"gorm.io/gorm")
type LiveState string
const(LiveScheduled LiveState="SCHEDULED";LiveLive LiveState="LIVE";LiveEnded LiveState="ENDED";LiveCancelled LiveState="CANCELLED")
type LiveSession struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;index" json:"channelId"`;OwnerID uint64 `gorm:"not null;index" json:"ownerId"`;Title string `gorm:"size:160;not null" json:"title"`;State LiveState `gorm:"size:16;not null;index" json:"state"`;PlaybackRef string `gorm:"size:512" json:"playbackRef,omitempty"`;StartedAt *time.Time `json:"startedAt,omitempty"`;EndedAt *time.Time `json:"endedAt,omitempty"`;CreatedAt time.Time `json:"createdAt"`;UpdatedAt time.Time `json:"updatedAt"`}
type MediaReference struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;index" json:"channelId"`;OwnerID uint64 `gorm:"not null;index" json:"ownerId"`;MediaID string `gorm:"size:160;not null;index" json:"mediaId"`;Access string `gorm:"size:16;not null" json:"access"`;Status string `gorm:"size:16;not null;index" json:"status"`;CreatedAt time.Time `json:"createdAt"`}
type SafetyCase struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;index" json:"channelId"`;ReporterID uint64 `gorm:"not null;index" json:"reporterId"`;TargetType string `gorm:"size:32;not null" json:"targetType"`;TargetID string `gorm:"size:160;not null" json:"targetId"`;Reason string `gorm:"size:80;not null" json:"reason"`;Status string `gorm:"size:24;not null;index" json:"status"`;Notes string `gorm:"type:text" json:"notes,omitempty"`;CreatedAt time.Time `json:"createdAt"`;UpdatedAt time.Time `json:"updatedAt"`}
type RightsRecord struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;index" json:"channelId"`;MediaID string `gorm:"size:160;not null;index" json:"mediaId"`;RightsType string `gorm:"size:40;not null" json:"rightsType"`;LicenseRef string `gorm:"size:256" json:"licenseRef,omitempty"`;Status string `gorm:"size:24;not null;index" json:"status"`;CreatedAt time.Time `json:"createdAt"`;UpdatedAt time.Time `json:"updatedAt"`}
type MonetizationEligibility struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;uniqueIndex" json:"channelId"`;Eligible bool `gorm:"not null;default:false" json:"eligible"`;Reason string `gorm:"size:256" json:"reason,omitempty"`;CheckedAt time.Time `json:"checkedAt"`}
type RevenueEvent struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;index" json:"channelId"`;UserID uint64 `gorm:"index" json:"userId,omitempty"`;EventType string `gorm:"size:48;not null;index" json:"eventType"`;ReferenceID string `gorm:"size:160;index" json:"referenceId,omitempty"`;GrossCents int64 `gorm:"not null" json:"grossCents"`;PlatformFeeCents int64 `gorm:"not null" json:"platformFeeCents"`;CreatorCents int64 `gorm:"not null" json:"creatorCents"`;Currency string `gorm:"size:8;not null;default:USD" json:"currency"`;Status string `gorm:"size:24;not null;index" json:"status"`;CreatedAt time.Time `json:"createdAt"`}
type AdCampaign struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;index" json:"channelId"`;OwnerID uint64 `gorm:"not null;index" json:"ownerId"`;Name string `gorm:"size:160;not null" json:"name"`;Status string `gorm:"size:24;not null;index" json:"status"`;BudgetCents int64 `gorm:"not null" json:"budgetCents"`;CreatedAt time.Time `json:"createdAt"`;UpdatedAt time.Time `json:"updatedAt"`}
type ChannelMetric struct{ID uint64 `gorm:"primaryKey" json:"id"`;ChannelID uint64 `gorm:"not null;index" json:"channelId"`;Metric string `gorm:"size:64;not null;index" json:"metric"`;Value int64 `gorm:"not null" json:"value"`;PeriodStart time.Time `gorm:"not null;index" json:"periodStart"`;PeriodEnd time.Time `gorm:"not null;index" json:"periodEnd"`}
func channelOwner(db *gorm.DB,c *gin.Context)(Channel,bool){var ch Channel;if db.First(&ch,c.Param("id")).Error!=nil||ch.Status==ChannelDisabled{c.JSON(404,gin.H{"message":"channel not found"});return ch,false};if ch.OwnerID!=userID(c){c.JSON(403,gin.H{"message":"channel owner required"});return ch,false};return ch,true}
func registerC6C8(db *gorm.DB,p *gin.RouterGroup){p.GET("/channels/:id/live",listLive(db));p.POST("/channels/:id/live",createLive(db));p.PATCH("/channels/:id/live/:sessionId",updateLive(db));p.POST("/channels/:id/live/:sessionId/start",startLive(db));p.POST("/channels/:id/live/:sessionId/end",endLive(db));p.DELETE("/channels/:id/live/:sessionId",cancelLive(db));p.GET("/channels/:id/media",listMediaRefs(db));p.POST("/channels/:id/media",addMediaRef(db));p.DELETE("/channels/:id/media/:mediaId",removeMediaRef(db));p.GET("/channels/:id/playback/:mediaId",playbackAuthorization(db));p.POST("/channels/:id/reports",reportCase(db));p.GET("/channels/:id/safety/cases",listCases(db));p.PATCH("/channels/:id/safety/cases/:caseId",updateCase(db));p.POST("/channels/:id/rights",setRights(db));p.GET("/channels/:id/rights",listRights(db));p.GET("/channels/:id/monetization",getEligibility(db));p.PUT("/channels/:id/monetization",setEligibility(db));p.POST("/channels/:id/revenue",recordRevenue(db));p.GET("/channels/:id/revenue",listRevenue(db));p.POST("/channels/:id/ads",createAd(db));p.GET("/channels/:id/ads",listAds(db));p.GET("/channels/:id/analytics",analytics(db))}
func listLive(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x []LiveSession;db.Where("channel_id=?",c.Param("id")).Order("created_at DESC").Limit(100).Find(&x);c.JSON(200,gin.H{"sessions":x})}}
func createLive(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var in struct{Title,PlaybackRef string};if c.ShouldBindJSON(&in)!=nil||strings.TrimSpace(in.Title)==""{c.JSON(400,gin.H{"message":"title is required"});return};x:=LiveSession{ChannelID:ch.ID,OwnerID:ch.OwnerID,Title:strings.TrimSpace(in.Title),State:LiveScheduled,PlaybackRef:strings.TrimSpace(in.PlaybackRef)};if err:=db.Create(&x).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to create live session"});return};c.JSON(201,x)}}
func updateLive(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var x LiveSession;if db.Where("id=? AND channel_id=?",c.Param("sessionId"),ch.ID).First(&x).Error!=nil{c.JSON(404,gin.H{"message":"live session not found"});return};var in struct{Title,PlaybackRef string};if c.ShouldBindJSON(&in)!=nil{c.JSON(400,gin.H{"message":"invalid request"});return};if x.State!=LiveScheduled{c.JSON(409,gin.H{"message":"live session is no longer editable"});return};if strings.TrimSpace(in.Title)!=""{x.Title=strings.TrimSpace(in.Title)};if in.PlaybackRef!=""{x.PlaybackRef=strings.TrimSpace(in.PlaybackRef)};db.Save(&x);c.JSON(200,x)}}
func transitionLive(db *gorm.DB,state LiveState)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var x LiveSession;if db.Where("id=? AND channel_id=?",c.Param("sessionId"),ch.ID).First(&x).Error!=nil{c.JSON(404,gin.H{"message":"live session not found"});return};now:=time.Now();if state==LiveLive&&x.State!=LiveScheduled{c.JSON(409,gin.H{"message":"only scheduled sessions can start"});return};if state==LiveEnded&&x.State!=LiveLive{c.JSON(409,gin.H{"message":"only live sessions can end"});return};x.State=state;if state==LiveLive{x.StartedAt=&now}else if state==LiveEnded{x.EndedAt=&now}else if state==LiveCancelled&&x.State==LiveLive{c.JSON(409,gin.H{"message":"live session must end before cancellation"});return};db.Save(&x);c.JSON(200,x)}}
func startLive(db *gorm.DB)gin.HandlerFunc{return transitionLive(db,LiveLive)}
func endLive(db *gorm.DB)gin.HandlerFunc{return transitionLive(db,LiveEnded)}
func cancelLive(db *gorm.DB)gin.HandlerFunc{return transitionLive(db,LiveCancelled)}
func listMediaRefs(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x []MediaReference;db.Where("channel_id=? AND status=?",c.Param("id"),"ACTIVE").Limit(100).Find(&x);c.JSON(200,gin.H{"media":x})}}
func addMediaRef(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var in struct{MediaID,Access string};if c.ShouldBindJSON(&in)!=nil||strings.TrimSpace(in.MediaID)==""{c.JSON(400,gin.H{"message":"mediaId is required"});return};if in.Access!="PRIVATE"{in.Access="PUBLIC"};x:=MediaReference{ChannelID:ch.ID,OwnerID:ch.OwnerID,MediaID:strings.TrimSpace(in.MediaID),Access:in.Access,Status:"ACTIVE"};if err:=db.Create(&x).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to link media"});return};c.JSON(201,x)}}
func removeMediaRef(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};db.Model(&MediaReference{}).Where("channel_id=? AND media_id=?",ch.ID,c.Param("mediaId")).Update("status","REMOVED");c.Status(204)}}
func playbackAuthorization(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x MediaReference;if db.Where("channel_id=? AND media_id=? AND status=?",c.Param("id"),c.Param("mediaId"),"ACTIVE").First(&x).Error!=nil{c.JSON(404,gin.H{"message":"media not found"});return};if x.Access=="PRIVATE"{c.JSON(200,gin.H{"allowed":false,"reason":"subscriber_entitlement_required","mediaId":x.MediaID});return};c.JSON(200,gin.H{"allowed":true,"mediaId":x.MediaID,"access":"PUBLIC"})}}
func reportCase(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var in struct{TargetType string `json:"targetType"`;TargetID string `json:"targetId"`;Reason string `json:"reason"`;Notes string `json:"notes"`};if c.ShouldBindJSON(&in)!=nil||in.TargetType==""||in.TargetID==""||in.Reason==""{c.JSON(400,gin.H{"message":"targetType, targetId and reason are required"});return};x:=SafetyCase{ChannelID:mustID(c.Param("id")),ReporterID:userID(c),TargetType:in.TargetType,TargetID:in.TargetID,Reason:in.Reason,Notes:in.Notes,Status:"OPEN"};db.Create(&x);c.JSON(201,x)}}
func listCases(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x []SafetyCase;db.Where("channel_id=?",c.Param("id")).Limit(100).Find(&x);c.JSON(200,gin.H{"cases":x})}}
func updateCase(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x SafetyCase;if db.Where("id=? AND channel_id=?",c.Param("caseId"),c.Param("id")).First(&x).Error!=nil{c.JSON(404,gin.H{"message":"case not found"});return};var in struct{Status string `json:"status"`;Notes string `json:"notes"`};if c.ShouldBindJSON(&in)!=nil||in.Status==""{c.JSON(400,gin.H{"message":"status is required"});return};switch in.Status{case "OPEN","REVIEWING","RESOLVED","REJECTED":default:c.JSON(400,gin.H{"message":"invalid status"});return};x.Status=in.Status;x.Notes=in.Notes;db.Save(&x);c.JSON(200,x)}}
func setRights(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var in struct{MediaID string `json:"mediaId"`;RightsType string `json:"rightsType"`;LicenseRef string `json:"licenseRef"`};if c.ShouldBindJSON(&in)!=nil||in.MediaID==""||in.RightsType==""{c.JSON(400,gin.H{"message":"mediaId and rightsType are required"});return};x:=RightsRecord{ChannelID:ch.ID,MediaID:in.MediaID,RightsType:in.RightsType,LicenseRef:in.LicenseRef,Status:"ACTIVE"};db.Create(&x);c.JSON(201,x)}}
func listRights(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x []RightsRecord;db.Where("channel_id=?",c.Param("id")).Find(&x);c.JSON(200,gin.H{"rights":x})}}
func getEligibility(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x MonetizationEligibility;if db.Where("channel_id=?",c.Param("id")).First(&x).Error!=nil{c.JSON(200,gin.H{"eligible":false,"reason":"not_reviewed"});return};c.JSON(200,x)}}
func setEligibility(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var in struct{Eligible bool `json:"eligible"`;Reason string `json:"reason"`};if c.ShouldBindJSON(&in)!=nil{c.JSON(400,gin.H{"message":"invalid request"});return};var x MonetizationEligibility;if db.Where("channel_id=?",ch.ID).First(&x).Error!=nil{x=MonetizationEligibility{ChannelID:ch.ID}};x.Eligible=in.Eligible;x.Reason=strings.TrimSpace(in.Reason);x.CheckedAt=time.Now();db.Save(&x);c.JSON(200,x)}}
func recordRevenue(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var in struct{UserID uint64 `json:"userId"`;EventType string `json:"eventType"`;ReferenceID string `json:"referenceId"`;Currency string `json:"currency"`;GrossCents int64 `json:"grossCents"`};if c.ShouldBindJSON(&in)!=nil||in.EventType==""||in.GrossCents<0{c.JSON(400,gin.H{"message":"eventType and valid grossCents are required"});return};fee:=in.GrossCents/5;x:=RevenueEvent{ChannelID:ch.ID,UserID:in.UserID,EventType:in.EventType,ReferenceID:in.ReferenceID,GrossCents:in.GrossCents,PlatformFeeCents:fee,CreatorCents:in.GrossCents-fee,Currency:in.Currency,Status:"PENDING"};if x.Currency==""{x.Currency="USD"};db.Create(&x);c.JSON(201,x)}}
func listRevenue(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x []RevenueEvent;db.Where("channel_id=?",c.Param("id")).Order("created_at DESC").Limit(100).Find(&x);c.JSON(200,gin.H{"events":x})}}
func createAd(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){ch,ok:=channelOwner(db,c);if !ok{return};var x AdCampaign;if c.ShouldBindJSON(&x)!=nil||strings.TrimSpace(x.Name)==""{c.JSON(400,gin.H{"message":"name is required"});return};x.ID=0;x.ChannelID=ch.ID;x.OwnerID=ch.OwnerID;if x.Status==""{x.Status="DRAFT"};db.Create(&x);c.JSON(201,x)}}
func listAds(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x []AdCampaign;db.Where("channel_id=?",c.Param("id")).Find(&x);c.JSON(200,gin.H{"ads":x})}}
func analytics(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var x []ChannelMetric;db.Where("channel_id=?",c.Param("id")).Order("period_end DESC").Limit(200).Find(&x);c.JSON(200,gin.H{"metrics":x})}}
func mustID(s string)uint64{var n uint64;for _,r:=range s{if r<'0'||r>'9'{return 0};n=n*10+uint64(r-'0')};return n}
