package main

import (
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/golang-jwt/jwt/v5"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

type Config struct { Port string; DatabaseURL string; JWTSecret string; FrontendURL string; Environment string }
func loadConfig() Config { return Config{Port:getenv("PORT","8080"),DatabaseURL:strings.TrimSpace(os.Getenv("DATABASE_URL")),JWTSecret:strings.TrimSpace(os.Getenv("JWT_SECRET")),FrontendURL:strings.TrimSpace(os.Getenv("FRONTEND_URL")),Environment:getenv("APP_ENV","development")} }
func getenv(k,fallback string) string { if v:=strings.TrimSpace(os.Getenv(k));v!=""{return v};return fallback }

type ChannelType string
const(ChannelPublic ChannelType="PUBLIC";ChannelPrivate ChannelType="PRIVATE")
type ChannelStatus string
const(ChannelActive ChannelStatus="ACTIVE";ChannelSuspended ChannelStatus="SUSPENDED";ChannelDisabled ChannelStatus="DISABLED")
type MembershipType string
const(MembershipFollower MembershipType="FOLLOWER";MembershipSubscriber MembershipType="SUBSCRIBER";MembershipTeam MembershipType="TEAM_MEMBER")
type Role string
const(RoleOwner Role="OWNER";RoleAdmin Role="ADMIN";RoleEditor Role="EDITOR";RoleBroadcaster Role="BROADCASTER";RoleModerator Role="MODERATOR";RoleAnalyst Role="ANALYST")

type Channel struct { ID uint64 `gorm:"primaryKey" json:"id"`; OwnerID uint64 `gorm:"not null;index" json:"ownerId"`; Slug string `gorm:"size:80;not null;uniqueIndex" json:"slug"`; Name string `gorm:"size:100;not null" json:"name"`; Description string `gorm:"type:text" json:"description,omitempty"`; AvatarMediaID string `gorm:"size:128" json:"avatarMediaId,omitempty"`; BannerMediaID string `gorm:"size:128" json:"bannerMediaId,omitempty"`; Category string `gorm:"size:80;index" json:"category,omitempty"`; Type ChannelType `gorm:"size:16;not null;index" json:"type"`; Status ChannelStatus `gorm:"size:16;not null;index" json:"status"`; CreatedAt time.Time `json:"createdAt"`; UpdatedAt time.Time `json:"updatedAt"` }
type ChannelMember struct { ID uint64 `gorm:"primaryKey" json:"id"`; ChannelID uint64 `gorm:"not null;uniqueIndex:idx_channel_member" json:"channelId"`; UserID uint64 `gorm:"not null;uniqueIndex:idx_channel_member;index" json:"userId"`; MembershipType MembershipType `gorm:"size:24;not null;index" json:"membershipType"`; Role Role `gorm:"size:24;not null;default:OWNER" json:"role"`; Status string `gorm:"size:16;not null;default:ACTIVE;index" json:"status"`; ExpiresAt *time.Time `json:"expiresAt,omitempty"`; CreatedAt time.Time `json:"createdAt"`; UpdatedAt time.Time `json:"updatedAt"` }
type ChannelPlan struct { ID uint64 `gorm:"primaryKey" json:"id"`; Code string `gorm:"size:40;uniqueIndex;not null" json:"code"`; Name string `gorm:"size:80;not null" json:"name"`; MonthlyPriceCents int64 `gorm:"not null" json:"monthlyPriceCents"`; StorageBytes int64 `gorm:"not null" json:"storageBytes"`; LiveMinutes int64 `gorm:"not null" json:"liveMinutes"`; ManagerLimit int `gorm:"not null" json:"managerLimit"`; PrivateAllowed bool `gorm:"not null" json:"privateAllowed"`; MonetizationAllowed bool `gorm:"not null" json:"monetizationAllowed"`; Active bool `gorm:"not null;default:true" json:"active"`; CreatedAt time.Time `json:"createdAt"`; UpdatedAt time.Time `json:"updatedAt"` }
type ChannelEntitlement struct { ID uint64 `gorm:"primaryKey" json:"id"`; ChannelID uint64 `gorm:"not null;uniqueIndex" json:"channelId"`; PlanCode string `gorm:"size:40;not null;index" json:"planCode"`; Status string `gorm:"size:16;not null;index" json:"status"`; StorageBytesUsed int64 `gorm:"not null;default:0" json:"storageBytesUsed"`; LiveMinutesUsed int64 `gorm:"not null;default:0" json:"liveMinutesUsed"`; PeriodEndsAt *time.Time `json:"periodEndsAt,omitempty"`; CreatedAt time.Time `json:"createdAt"`; UpdatedAt time.Time `json:"updatedAt"` }
type Claims struct { UserID uint64 `json:"userId"`; Email string `json:"email"`; jwt.RegisteredClaims }

func auth(secret string) gin.HandlerFunc{return func(c *gin.Context){token:="";if h:=strings.TrimSpace(c.GetHeader("Authorization"));h!=""{p:=strings.Fields(h);if len(p)!=2||!strings.EqualFold(p[0],"Bearer"){c.AbortWithStatusJSON(401,gin.H{"message":"Invalid authorization header format"});return};token=p[1]};if token==""{token,_=c.Cookie("auth_token")};if token==""{c.AbortWithStatusJSON(401,gin.H{"message":"Authentication required"});return};claims:=&Claims{};t,err:=jwt.ParseWithClaims(token,claims,func(t *jwt.Token)(any,error){if t.Method!=jwt.SigningMethodHS256{return nil,errors.New("unexpected signing method")};return []byte(secret),nil},jwt.WithIssuer("notell-api"));if err!=nil||!t.Valid||claims.UserID==0{c.AbortWithStatusJSON(401,gin.H{"message":"Invalid or expired token"});return};c.Set("userId",claims.UserID);c.Set("email",claims.Email);c.Next()}}
func userID(c *gin.Context)uint64{v,_:=c.Get("userId");id,_:=v.(uint64);return id}
var slugRE=regexp.MustCompile(`[^a-z0-9]+`)
func makeSlug(name string)string{s:=strings.ToLower(strings.TrimSpace(name));s=slugRE.ReplaceAllString(s,"-");return strings.Trim(s,"-")}

func main(){cfg:=loadConfig();if cfg.DatabaseURL==""{log.Fatal("DATABASE_URL is required")};if cfg.JWTSecret==""{log.Fatal("JWT_SECRET is required")};db,err:=gorm.Open(postgres.Open(cfg.DatabaseURL),&gorm.Config{});if err!=nil{log.Fatalf("database connection failed: %v",err)};if err:=db.AutoMigrate(&Channel{},&ChannelMember{},&ChannelPlan{},&ChannelEntitlement{},&ChannelTeamMember{},&ChannelInvitation{},&ChannelProgram{},&ChannelSchedule{},&ChannelContent{},&ChannelSetting{});err!=nil{log.Fatalf("migration failed: %v",err)};if err:=repairMembershipIndex(db);err!=nil{log.Fatalf("membership index repair failed: %v",err)};seedPlans(db)
	r:=gin.New();r.Use(gin.Logger(),gin.Recovery());cc:=cors.DefaultConfig();cc.AllowCredentials=true;cc.AllowHeaders=[]string{"Origin","Content-Type","Accept","Authorization"};if cfg.FrontendURL!=""{cc.AllowOrigins=[]string{cfg.FrontendURL}}else{cc.AllowAllOrigins=true;cc.AllowCredentials=false};r.Use(cors.New(cc));r.GET("/health",func(c *gin.Context){c.JSON(200,gin.H{"status":"ok","service":"channel"})});r.GET("/ready",func(c *gin.Context){sqlDB,e:=db.DB();if e!=nil||sqlDB.Ping()!=nil{c.JSON(503,gin.H{"status":"not_ready"});return};c.JSON(200,gin.H{"status":"ready","service":"channel"})})
	v1:=r.Group("/v1");v1.GET("/channels",listChannels(db));v1.GET("/channels/:id",getChannel(db));protected:=v1.Group("",auth(cfg.JWTSecret));protected.POST("/channels",createChannel(db));protected.PATCH("/channels/:id",updateChannel(db));protected.DELETE("/channels/:id",deleteChannel(db));protected.POST("/channels/:id/follow",followChannel(db,MembershipFollower));protected.DELETE("/channels/:id/follow",unfollowChannel(db));protected.GET("/channels/:id/members",listMembers(db));protected.POST("/channels/:id/members",addMember(db));protected.DELETE("/channels/:id/members/:userId",removeMember(db));protected.POST("/channels/:id/subscribe",followChannel(db,MembershipSubscriber));protected.DELETE("/channels/:id/subscribe",unsubscribeChannel(db));
	protected.GET("/channels/:id/team",listTeam(db));protected.POST("/channels/:id/team/invitations",inviteTeam(db));protected.POST("/channels/:id/team/invitations/:invitationId/accept",acceptTeamInvite(db));protected.PATCH("/channels/:id/team/:userId",updateTeam(db));protected.DELETE("/channels/:id/team/:userId",removeTeam(db));
	protected.GET("/channels/:id/studio/programs",programs(db));protected.POST("/channels/:id/studio/programs",createProgram(db));protected.PATCH("/channels/:id/studio/programs/:programId",updateProgram(db));protected.DELETE("/channels/:id/studio/programs/:programId",deleteProgram(db));protected.GET("/channels/:id/studio/schedule",schedules(db));protected.POST("/channels/:id/studio/schedule",createSchedule(db));protected.PATCH("/channels/:id/studio/schedule/:scheduleId",updateSchedule(db));protected.DELETE("/channels/:id/studio/schedule/:scheduleId",deleteSchedule(db));protected.GET("/channels/:id/studio/content",content(db));protected.POST("/channels/:id/studio/content",linkContent(db));protected.PATCH("/channels/:id/studio/content/:contentId",updateContent(db));protected.DELETE("/channels/:id/studio/content/:contentId",unlinkContent(db));protected.GET("/channels/:id/studio/audience",audience(db));protected.GET("/channels/:id/studio/settings",studioSettings(db));protected.PUT("/channels/:id/studio/settings/:key",setStudioSetting(db))
	addr:=":"+cfg.Port;if err:=http.ListenAndServe(addr,r);err!=nil{log.Fatal(err)}}

func seedPlans(db *gorm.DB){plans:=[]ChannelPlan{{Code:"STARTER",Name:"Starter",MonthlyPriceCents:399,StorageBytes:50*1024*1024*1024,LiveMinutes:600,ManagerLimit:1,PrivateAllowed:false,MonetizationAllowed:false,Active:true},{Code:"CREATOR",Name:"Creator",MonthlyPriceCents:999,StorageBytes:250*1024*1024*1024,LiveMinutes:3000,ManagerLimit:3,PrivateAllowed:true,MonetizationAllowed:true,Active:true},{Code:"STUDIO",Name:"Studio",MonthlyPriceCents:2499,StorageBytes:1024*1024*1024*1024,LiveMinutes:9000,ManagerLimit:10,PrivateAllowed:true,MonetizationAllowed:true,Active:true},{Code:"PRO_NETWORK",Name:"Pro Network",MonthlyPriceCents:5999,StorageBytes:3*1024*1024*1024*1024,LiveMinutes:24000,ManagerLimit:25,PrivateAllowed:true,MonetizationAllowed:true,Active:true}};for _,p:=range plans{var existing ChannelPlan;if errors.Is(db.Where("code = ?",p.Code).First(&existing).Error,gorm.ErrRecordNotFound){db.Create(&p)}}}
func listChannels(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var rows []Channel;q:=db.Where("status = ?",ChannelActive);if cat:=strings.TrimSpace(c.Query("category"));cat!=""{q=q.Where("category = ?",cat)};if search:=strings.TrimSpace(c.Query("search"));search!=""{q=q.Where("name ILIKE ? OR description ILIKE ?","%"+search+"%","%"+search+"%")};if err:=q.Order("created_at DESC,id DESC").Limit(50).Find(&rows).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to list channels"});return};c.JSON(200,gin.H{"channels":rows})}}
func getChannel(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var ch Channel;if err:=db.First(&ch,c.Param("id")).Error;err!=nil||ch.Status!=ChannelActive{c.JSON(404,gin.H{"message":"channel not found"});return};c.JSON(200,ch)}}
type createInput struct{Name string `json:"name"`;Description string `json:"description"`;Category string `json:"category"`;Type ChannelType `json:"type"`;AvatarMediaID string `json:"avatarMediaId"`;BannerMediaID string `json:"bannerMediaId"`}
func createChannel(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var in createInput;if c.ShouldBindJSON(&in)!=nil{c.JSON(400,gin.H{"message":"invalid request body"});return};in.Name=strings.TrimSpace(in.Name);if len(in.Name)<2||len(in.Name)>100{c.JSON(400,gin.H{"message":"name must be between 2 and 100 characters"});return};if in.Type==""{in.Type=ChannelPublic};if in.Type!=ChannelPublic&&in.Type!=ChannelPrivate{c.JSON(400,gin.H{"message":"invalid channel type"});return};slug:=makeSlug(in.Name);if slug==""{c.JSON(400,gin.H{"message":"name cannot produce a valid slug"});return};for i:=0;;i++{candidate:=slug;if i>0{candidate=fmt.Sprintf("%s-%d",slug,i+1)};var n int64;db.Model(&Channel{}).Where("slug = ?",candidate).Count(&n);if n==0{slug=candidate;break}};ch:=Channel{OwnerID:userID(c),Name:in.Name,Slug:slug,Description:strings.TrimSpace(in.Description),Category:strings.TrimSpace(in.Category),Type:in.Type,Status:ChannelActive,AvatarMediaID:strings.TrimSpace(in.AvatarMediaID),BannerMediaID:strings.TrimSpace(in.BannerMediaID)};err:=db.Transaction(func(tx *gorm.DB)error{if err:=tx.Create(&ch).Error;err!=nil{return err};m:=ChannelMember{ChannelID:ch.ID,UserID:userID(c),MembershipType:MembershipTeam,Role:RoleOwner,Status:"ACTIVE"};if err:=tx.Create(&m).Error;err!=nil{return err};return tx.Create(&ChannelEntitlement{ChannelID:ch.ID,PlanCode:"CREATOR",Status:"PENDING"}).Error});if err!=nil{c.JSON(500,gin.H{"message":"failed to create channel"});return};c.JSON(201,ch)}}
func updateChannel(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var ch Channel;if db.First(&ch,c.Param("id")).Error!=nil{c.JSON(404,gin.H{"message":"channel not found"});return};if ch.OwnerID!=userID(c){c.JSON(403,gin.H{"message":"owner access required"});return};var in createInput;if c.ShouldBindJSON(&in)!=nil{c.JSON(400,gin.H{"message":"invalid request body"});return};if strings.TrimSpace(in.Name)!=""{ch.Name=strings.TrimSpace(in.Name)};if in.Description!=""{ch.Description=strings.TrimSpace(in.Description)};if in.Category!=""{ch.Category=strings.TrimSpace(in.Category)};if in.Type!=""{if in.Type!=ChannelPublic&&in.Type!=ChannelPrivate{c.JSON(400,gin.H{"message":"invalid channel type"});return};ch.Type=in.Type};if in.AvatarMediaID!=""{ch.AvatarMediaID=strings.TrimSpace(in.AvatarMediaID)};if in.BannerMediaID!=""{ch.BannerMediaID=strings.TrimSpace(in.BannerMediaID)};if err:=db.Save(&ch).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to update channel"});return};c.JSON(200,ch)}}
func deleteChannel(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var ch Channel;if db.First(&ch,c.Param("id")).Error!=nil{c.JSON(404,gin.H{"message":"channel not found"});return};if ch.OwnerID!=userID(c){c.JSON(403,gin.H{"message":"owner access required"});return};if err:=db.Model(&ch).Update("status",ChannelDisabled).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to disable channel"});return};c.Status(204)}}
func followChannel(db *gorm.DB,kind MembershipType)gin.HandlerFunc{return func(c *gin.Context){id:=c.Param("id");var ch Channel;if db.First(&ch,id).Error!=nil||ch.Status!=ChannelActive{c.JSON(404,gin.H{"message":"channel not found"});return};var m ChannelMember;err:=db.Where("channel_id=? AND user_id=? AND membership_type=?",ch.ID,userID(c),kind).First(&m).Error;if errors.Is(err,gorm.ErrRecordNotFound){m=ChannelMember{ChannelID:ch.ID,UserID:userID(c),MembershipType:kind,Role:"",Status:"ACTIVE"};if err:=db.Create(&m).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to join channel"});return}}else if err!=nil{c.JSON(500,gin.H{"message":"failed to load membership"});return}else{m.Status="ACTIVE";if err:=db.Save(&m).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to update membership"});return}};c.JSON(200,gin.H{"message":"membership updated","membershipType":kind})}}
func unfollowChannel(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){removeMembership(db,c,MembershipFollower)}}
func unsubscribeChannel(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){removeMembership(db,c,MembershipSubscriber)}}
func removeMembership(db *gorm.DB,c *gin.Context,kind MembershipType){var m ChannelMember;if err:=db.Where("channel_id=? AND user_id=? AND membership_type=?",c.Param("id"),userID(c),kind).First(&m).Error;err!=nil{c.JSON(404,gin.H{"message":"membership not found"});return};db.Delete(&m);c.Status(204)}
func listMembers(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var rows []ChannelMember;if err:=db.Where("channel_id=?",c.Param("id")).Order("created_at ASC,id ASC").Limit(100).Find(&rows).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to list members"});return};c.JSON(200,gin.H{"members":rows})}}
type memberInput struct{UserID uint64 `json:"userId"`;Role Role `json:"role"`}
func addMember(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var ch Channel;if db.First(&ch,c.Param("id")).Error!=nil{c.JSON(404,gin.H{"message":"channel not found"});return};if ch.OwnerID!=userID(c){c.JSON(403,gin.H{"message":"owner access required"});return};var in memberInput;if c.ShouldBindJSON(&in)!=nil||in.UserID==0{c.JSON(400,gin.H{"message":"valid userId is required"});return};role:=in.Role;if role==""{role=RoleEditor};switch role{case RoleAdmin,RoleEditor,RoleBroadcaster,RoleModerator,RoleAnalyst:default:c.JSON(400,gin.H{"message":"invalid team role"});return};m:=ChannelMember{ChannelID:ch.ID,UserID:in.UserID,MembershipType:MembershipTeam,Role:role,Status:"ACTIVE"};if err:=db.Where("channel_id=? AND user_id=?",ch.ID,in.UserID).Assign(map[string]any{"membership_type":MembershipTeam,"role":role,"status":"ACTIVE"}).FirstOrCreate(&m).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to add team member"});return};c.JSON(201,m)}}
func removeMember(db *gorm.DB)gin.HandlerFunc{return func(c *gin.Context){var ch Channel;if db.First(&ch,c.Param("id")).Error!=nil{c.JSON(404,gin.H{"message":"channel not found"});return};if ch.OwnerID!=userID(c){c.JSON(403,gin.H{"message":"owner access required"});return};if c.Param("userId")==fmt.Sprint(ch.OwnerID){c.JSON(409,gin.H{"message":"owner cannot be removed"});return};if err:=db.Where("channel_id=? AND user_id=?",ch.ID,c.Param("userId")).Delete(&ChannelMember{}).Error;err!=nil{c.JSON(500,gin.H{"message":"failed to remove member"});return};c.Status(204)}}
