package main

import("sort";"strings";"sync";"time")
type MusicEvent struct{TrackID string `json:"trackId"`;Type string `json:"type"`;Country string `json:"country,omitempty"`;City string `json:"city,omitempty"`;UserID string `json:"userId,omitempty"`;At time.Time `json:"at"`}
type TrendItem struct{TrackID string `json:"trackId"`;Score float64 `json:"score"`;Plays int64 `json:"plays"`;Uses int64 `json:"uses"`;Saves int64 `json:"saves"`;Shares int64 `json:"shares"`;Growth24h float64 `json:"growth24h"`;Country string `json:"country,omitempty"`;City string `json:"city,omitempty"`}
type TrendStore interface{Add(MusicEvent)error;Rank(string,string,time.Duration)([]TrendItem,error)}
type memoryTrendStore struct{mu sync.RWMutex;events []MusicEvent}
var trends TrendStore=&memoryTrendStore{}
var eventWeights=map[string]float64{"play":1,"complete":2,"replay":2,"use":8,"save":5,"share":6,"search":0.25}
func(s *memoryTrendStore)Add(e MusicEvent)error{if e.At.IsZero(){e.At=time.Now().UTC()};e.Type=strings.ToLower(strings.TrimSpace(e.Type));if _,ok:=eventWeights[e.Type];!ok{return nil};s.mu.Lock();defer s.mu.Unlock();s.events=append(s.events,e);if len(s.events)>100000{s.events=s.events[len(s.events)-100000:]};return nil}
func(s *memoryTrendStore)Rank(country,city string,window time.Duration)([]TrendItem,error){now:=time.Now().UTC();cutoff:=now.Add(-window);previous:=cutoff.Add(-window);type agg struct{score,previous float64;plays,uses,saves,shares int64};totals:=map[string]*agg{};s.mu.RLock();events:=make([]MusicEvent,len(s.events));copy(events,s.events);s.mu.RUnlock();for _,e:=range events{if e.At.Before(previous)||e.At.After(now)||country!=""&&!strings.EqualFold(e.Country,country)||city!=""&&!strings.EqualFold(e.City,city){continue};a:=totals[e.TrackID];if a==nil{a=&agg{};totals[e.TrackID]=a};w:=eventWeights[e.Type];if e.At.Before(cutoff){a.previous+=w;continue};a.score+=w;switch e.Type{case"play","complete","replay":a.plays++;case"use":a.uses++;case"save":a.saves++;case"share":a.shares++}};result:=make([]TrendItem,0,len(totals));for id,a:=range totals{growth:=0.0;if a.previous>0{growth=(a.score-a.previous)/a.previous*100};result=append(result,TrendItem{TrackID:id,Score:a.score,Plays:a.plays,Uses:a.uses,Saves:a.saves,Shares:a.shares,Growth24h:growth,Country:country,City:city})};sort.Slice(result,func(i,j int)bool{if result[i].Score==result[j].Score{return result[i].TrackID<result[j].TrackID};return result[i].Score>result[j].Score});if len(result)>50{result=result[:50]};return result,nil}
