import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, Check, Loader2, Radio } from "lucide-react";
import { paymentAPI } from "../services/payment/paymentApi";

export default function PlansPage(){
 const [packages,setPackages]=useState([]); const [active,setActive]=useState(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
 useEffect(()=>{Promise.all([paymentAPI.packages(),paymentAPI.subscriptions()]).then(([p,s])=>{setPackages(p.packages||[]);const rows=s.subscriptions||[];setActive(rows.find(x=>["active","trialing","past_due","canceled"].includes(x.status)&&new Date(x.currentPeriodEnd)>new Date())||null)}).catch(e=>setError(e?.response?.data?.error||"Unable to load plans.")).finally(()=>setLoading(false))},[]);
 const choose=async id=>{setBusy(id);setError("");try{const sub=await paymentAPI.subscribe(id);const row=sub.subscription;if(sub.payment_required===false){setActive(row);return}const checkout=await paymentAPI.checkout(row.id);if(checkout.url)window.location.assign(checkout.url);else setError("Checkout URL was not returned.")}catch(e){setError(e?.response?.data?.error||"Unable to start subscription checkout.")}finally{setBusy("")}};
 return <section className="min-h-screen w-full bg-neutral-950 px-4 pb-28 pt-5 text-neutral-100"><div className="mx-auto max-w-5xl"><Link to="/channels" className="inline-flex items-center gap-2 text-xs font-bold text-neutral-500 hover:text-white"><ArrowLeft size={16}/> Channels</Link><header className="mt-6"><div className="flex items-center gap-3"><Radio size={22}/><h1 className="text-2xl font-black">Channel & Live plans</h1></div><p className="mt-2 max-w-2xl text-sm text-neutral-500">Choose a monthly plan to create and manage channels and unlock live-streaming capabilities. Public channels remain viewable without a creator plan.</p></header>{active&&<div className="mt-5 rounded-2xl border border-neutral-700 bg-neutral-900/70 p-4 text-sm"><span className="font-black">Active plan:</span> {active.packageId} · {active.status}</div>}{error&&<div className="mt-5 rounded-xl border border-red-900/40 bg-red-950/20 p-3 text-xs text-red-300">{error}</div>}{loading?<div className="flex min-h-60 items-center justify-center"><Loader2 className="animate-spin text-neutral-600"/></div>:<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{packages.map(p=><article key={p.id} className="rounded-3xl border border-neutral-800 bg-neutral-900/60 p-5"><h2 className="text-lg font-black">{p.name}</h2><p className="mt-2 min-h-16 text-xs leading-5 text-neutral-500">{p.description}</p><div className="mt-5 text-2xl font-black">{new Intl.NumberFormat(undefined,{style:"currency",currency:String(p.currency||"USD").toUpperCase(),maximumFractionDigits:2}).format(Number(p.monthly_price||0)/100)}<span className="text-xs font-normal text-neutral-600"> / month</span></div><div className="mt-5 space-y-2 text-xs text-neutral-400"><p className="flex gap-2"><Check size={14}/> Live streaming allowance</p><p className="flex gap-2"><Check size={14}/> Viewer delivery allowance</p><p className="flex gap-2"><Check size={14}/> Storage allowance</p></div><button onClick={()=>choose(p.id)} disabled={!!busy||!!active} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-neutral-100 px-4 py-3 text-xs font-black text-neutral-950 disabled:opacity-40">{busy===p.id?<Loader2 size={14} className="animate-spin"/>:active?"Active plan":"Choose plan"}</button></article>)}</div>}</div></section>
}
