import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, Bell, ChevronRight, CircleHelp, Database, Download, FileText, History, Info, LogOut, Mail, Megaphone, PlaySquare, ShieldCheck, SlidersHorizontal, UserRound, Wifi, X } from "lucide-react";
import { useAuth } from "../context/AuthContext";

const Section = ({ title, children }) => <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-4 py-3 sm:px-5"><h2 className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">{title}</h2></div><div className="divide-y divide-slate-100">{children}</div></section>;
const Row = ({ icon: Icon, title, description, to, onClick }) => { const body = <><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-700"><Icon size={18}/></span><span className="min-w-0 flex-1 text-left"><span className="block text-sm font-semibold text-slate-900">{title}</span><span className="mt-0.5 block text-xs leading-5 text-slate-500">{description}</span></span><ChevronRight size={18} className="shrink-0 text-slate-300"/></>; return to ? <Link to={to} className="flex items-center gap-3 px-4 py-3.5 transition hover:bg-slate-50 sm:px-5">{body}</Link> : <button type="button" onClick={onClick} className="flex w-full items-center gap-3 px-4 py-3.5 transition hover:bg-slate-50 sm:px-5">{body}</button>; };
const Toggle = ({ icon: Icon, title, description, checked, onChange }) => <label className="flex cursor-pointer items-center gap-3 px-4 py-3.5 hover:bg-slate-50 sm:px-5"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-700"><Icon size={18}/></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-slate-900">{title}</span><span className="mt-0.5 block text-xs leading-5 text-slate-500">{description}</span></span><input className="sr-only" type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)}/><span className={`relative h-6 w-11 rounded-full transition ${checked ? "bg-indigo-600" : "bg-slate-200"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${checked ? "left-6" : "left-1"}`}/></span></label>;

export default function SettingsPage() {
  const { logout } = useAuth(); const navigate = useNavigate();
  const [dataSaver,setDataSaver] = useState(() => localStorage.getItem("notell:dataSaver") === "true");
  const [autoplay,setAutoplay] = useState(() => localStorage.getItem("notell:autoplay") !== "false");
  const [message,setMessage] = useState(""); const [confirmLogout,setConfirmLogout] = useState(false);
  const save = (key,value,setter) => { setter(value); localStorage.setItem(key,String(value)); };
  const clearCache = () => { setMessage("Local Notell cache cleared."); setTimeout(() => setMessage(""),2500); };
  const doLogout = async () => { try { await logout(); } finally { navigate("/auth",{replace:true}); } };
  const unavailable = label => setMessage(`${label} is ready for configuration in the next settings update.`);
  return <div className="min-h-screen bg-slate-50 pb-10">
    <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-14 max-w-3xl items-center gap-3 px-3 sm:px-6"><button type="button" onClick={() => navigate(-1)} aria-label="Back" className="inline-flex h-9 w-9 items-center justify-center rounded-full text-slate-700 hover:bg-slate-100"><ArrowLeft size={20}/></button><div><h1 className="text-base font-bold text-slate-950">Settings</h1><p className="text-[10px] text-slate-500">Manage your Notell experience</p></div></div></header>
    <main className="mx-auto max-w-3xl space-y-4 px-3 pt-5 sm:px-6 sm:pt-7"><div><h2 className="text-xl font-bold text-slate-950">Notell settings</h2><p className="mt-1 text-sm text-slate-500">Manage your account, activity, data, privacy and website preferences.</p></div>
      {message && <div className="flex items-center justify-between rounded-2xl border border-indigo-100 bg-indigo-50 px-4 py-3 text-xs font-medium text-indigo-700"><span>{message}</span><button type="button" onClick={() => setMessage("")}><X size={15}/></button></div>}
      <Section title="Account"><Row icon={UserRound} title="Edit profile" description="Profile picture, name, bio and profile details" to="/profile"/><Row icon={ShieldCheck} title="Manage and privacy" description="Privacy, followers and account controls" to="/settings/privacy"/></Section>
      <Section title="Activities"><Row icon={PlaySquare} title="Contents" description="Control what you see and how content is shown" onClick={() => unavailable("Contents")}/><Row icon={Bell} title="Notifications" description="Choose which notifications you receive" onClick={() => unavailable("Notifications")}/><Row icon={Megaphone} title="Ads" description="Manage ad preferences and personalization" onClick={() => unavailable("Ads")}/><Row icon={History} title="History" description="View and clear your activity history" onClick={() => unavailable("History")}/></Section>
      <Section title="Data"><Row icon={Download} title="Media downloads" description="Control automatic and manual media downloads" onClick={() => unavailable("Media downloads")}/><Row icon={Database} title="Cache and storage" description="Manage cached media and local storage" onClick={clearCache}/><Row icon={SlidersHorizontal} title="Storage settings" description="Choose how Notell uses device storage" onClick={() => unavailable("Storage settings")}/><Toggle icon={Wifi} title="Data saver" description="Reduce media loading and bandwidth usage" checked={dataSaver} onChange={v => save("notell:dataSaver",v,setDataSaver)}/></Section>
      <Section title="About"><Row icon={Info} title="About Notell" description="Learn about the website and its features" onClick={() => unavailable("About Notell")}/><Row icon={FileText} title="Rules and terms" description="Community rules, terms of service and policies" onClick={() => unavailable("Rules and terms")}/><Row icon={CircleHelp} title="More" description="Additional information and resources" onClick={() => unavailable("More")}/></Section>
      <Section title="Contacts and help"><Row icon={CircleHelp} title="Help center" description="Find answers and troubleshooting guides" onClick={() => unavailable("Help center")}/><Row icon={Mail} title="Email" description="Contact the Notell team" onClick={() => unavailable("Email")}/></Section>
      <Section title="Media preference"><Toggle icon={PlaySquare} title="Autoplay videos" description="Automatically play videos in your feed" checked={autoplay} onChange={v => save("notell:autoplay",v,setAutoplay)}/></Section>
      <button type="button" onClick={() => setConfirmLogout(true)} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-red-200 bg-white px-5 py-3.5 text-sm font-bold text-red-600 shadow-sm hover:bg-red-50"><LogOut size={17}/> Logout</button><p className="pb-2 text-center text-[10px] text-slate-400">Notell settings • Preferences are saved on this device</p>
    </main>
    {confirmLogout && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-sm"><div className="w-full max-w-sm rounded-3xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-950">Log out?</h2><button onClick={() => setConfirmLogout(false)}><X size={18}/></button></div><p className="mt-2 text-sm text-slate-500">You will need to sign in again to access your account.</p><div className="mt-5 flex gap-2"><button onClick={() => setConfirmLogout(false)} className="flex-1 rounded-xl border px-4 py-2.5 text-sm font-semibold">Cancel</button><button onClick={doLogout} className="flex-1 rounded-xl bg-red-600 px-4 py-2.5 text-sm font-semibold text-white">Log out</button></div></div></div>}
  </div>;
}
