package main

import (
 "crypto/rand"
 "encoding/hex"
 "errors"
 "log"
 "net/http"
 "os"
 "strconv"
 "strings"
 "sync"
 "time"

 "github.com/gin-contrib/cors"
 "github.com/gin-gonic/gin"
 "github.com/golang-jwt/jwt/v5"
 "github.com/gorilla/websocket"
 "github.com/livekit/protocol/auth"
 "gorm.io/driver/postgres"
 "gorm.io/gorm"
)

const ( messageTypeText="TEXT"; conversationDirect="DIRECT"; conversationGroup="GROUP"; callActive="ACTIVE"; callEnded="ENDED" )
type Config struct { Port,DatabaseURL,JWTSecret,FrontendURL,AppEnv,LiveKitURL,LiveKitKey,LiveKitSecret string }
func loadConfig()(Config,error){c:=Config{Port:env("PORT","8080"),AppEnv:env("APP_ENV","development"),FrontendURL:os.Getenv("FRONTEND_URL"),LiveKitURL:os.Getenv("LIVEKIT_URL"),LiveKitKey:os.Getenv("LIVEKIT_API_KEY"),LiveKitSecret:os.Getenv("LIVEKIT_API_SECRET"),DatabaseURL:os.Getenv("DATABASE_URL"),JWTSecret:os.Getenv("JWT_SECRET")};if c.DatabaseURL==""||c.JWTSecret==""{return c,errors.New("DATABASE_URL and JWT_SECRET are required")};return c,nil}
func env(k,d string)string{if v:=os.Getenv(k);v!=""{return v};return d}
type Conversation struct{ID string `gorm:"primaryKey;size:32" json:"id"`;Type string `gorm:"size:16;not null" json:"type"`;Title string `gorm:"size:160" json:"title"`;CreatedBy string `gorm:"size:128;not null;index" json:"createdBy"`;CreatedAt time.Time `json:"createdAt"`;UpdatedAt time.Time `json:"updatedAt"`}
type ConversationMember struct{ID uint `gorm:"primaryKey"`;ConversationID string `gorm:"size:32;not null;uniqueIndex:ux_conv_member"`;UserID string `gorm:"size:128;not null;uniqueIndex:ux_conv_member;index"`;JoinedAt time.Time `json:"joinedAt"`}
type Message struct{ID string `gorm:"primaryKey;size:32" json:"id"`;ConversationID string `gorm:"size:32;not null;index" json:"conversationId"`;SenderID string `gorm:"size:128;not null;index" json:"senderId"`;Type string `gorm:"size:24;not null" json:"type"`;Body string `gorm:"type:text" json:"body"`;ClientID string `gorm:"size:64;index" json:"clientId"`;CreatedAt time.Time `json:"createdAt"`}
type ReadReceipt struct{ID uint `gorm:"primaryKey"`;MessageID string `gorm:"size:32;not null;uniqueIndex:ux_read"`;UserID string `gorm:"size:128;not null;uniqueIndex:ux_read"`;ReadAt time.Time `json:"readAt"`}
type Call struct{ID string `gorm:"primaryKey;size:32" json:"id"`;ConversationID string `gorm:"size:32;not null;index" json:"conversationId"`;RoomName string `gorm:"size:160;not null;uniqueIndex" json:"roomName"`;CreatedBy string `gorm:"size:128;not null" json:"createdBy"`;Status string `gorm:"size:16;not null;index" json:"status"`;CreatedAt time.Time `json:"createdAt"`;EndedAt *time.Time `json:"endedAt,omitempty"`}
func newID()string{b:=make([]byte,16);_,_=rand.Read(b);return hex.EncodeToString(b)}
func userIDFromJWT(c *gin.Context,secret string)(string,bool){token:="";if h:=c.GetHeader("Authorization");strings.HasPrefix(h,"Bearer "){token=strings.TrimSpace(strings.TrimPrefix(h,"Bearer "))};if token==""{token,_=c.Cookie("auth_token")};if token==""{return "",false};p,e:=jwt.Parse(token,func(t *jwt.Token)(any,error){if t.Method!=jwt.SigningMethodHS256{return nil,errors.New("unexpected signing method")};return []byte(secret),nil},jwt.WithIssuer("notell-api"));if e!=nil||!p.Valid{return "",false};claims,ok:=p.Claims.(jwt.MapClaims);if !ok{return "",false};for _,k:=range []string{"userId","user_id","sub"}{if v,ok:=claims[k].(string);ok&&v!=""{return v,true}};return "",false}
func authMW(secret string)gin.HandlerFunc{return func(c *gin.Context){id,ok:=userIDFromJWT(c,secret);if !ok{c.AbortWithStatusJSON(401,gin.H{"error":"unauthorized"});return};c.Set("userID",id);c.Next()}}
func uid(c *gin.Context)string{v,_:=c.Get("userID");return v.(string)}

type safeSocket struct{mu sync.Mutex;conn *websocket.Conn}
func(s *safeSocket)write(v any)error{s.mu.Lock();defer s.mu.Unlock();_=s.conn.SetWriteDeadline(time.Now().Add(10*time.Second));return s.conn.WriteJSON(v)}
func(s *safeSocket)ping()error{s.mu.Lock();defer s.mu.Unlock();_=s.conn.SetWriteDeadline(time.Now().Add(10*time.Second));return s.conn.WriteControl(websocket.PingMessage,[]byte("ping"),time.Now().Add(5*time.Second))}
type hub struct{mu sync.RWMutex;clients map[string]map[*safeSocket]struct{}}
func newHub()*hub{return &hub{clients:map[string]map[*safeSocket]struct{}{}}}
func(h *hub)add(conv string,ws *safeSocket){h.mu.Lock();defer h.mu.Unlock();if h.clients[conv]==nil{h.clients[conv]=map[*safeSocket]struct{}{}};h.clients[conv][ws]=struct{}{}}
func(h *hub)remove(conv string,ws *safeSocket){h.mu.Lock();defer h.mu.Unlock();if m:=h.clients[conv];m!=nil{delete(m,ws);if len(m)==0{delete(h.clients,conv)}}}
func(h *hub)broadcast(conv string,v any){h.mu.RLock();list:=make([]*safeSocket,0,len(h.clients[conv]));for ws:=range h.clients[conv]{list=append(list,ws)};h.mu.RUnlock();for _,ws:=range list{if ws.write(v)!=nil{_ = ws.conn.Close();h.remove(conv,ws)}}}
func member(db *gorm.DB,conv,user string)bool{var m ConversationMember;return db.Where("conversation_id=? AND user_id=?",conv,user).First(&m).Error==nil}
func requireMember(db *gorm.DB,c *gin.Context,conv string)bool{if !member(db,conv,uid(c)){c.JSON(403,gin.H{"error":"conversation membership required"});return false};return true}
func callToken(key,secret,room,user string)(string,error){at:=auth.NewAccessToken(key,secret);at.SetIdentity(user).SetValidFor(2*time.Hour);at.SetVideoGrant(&auth.VideoGrant{RoomJoin:true,Room:room});return at.ToJWT()}
func expireStaleCalls(db *gorm.DB,h *hub){cutoff:=time.Now().Add(-2*time.Hour);var calls []Call;if e:=db.Where("status=? AND created_at < ?",callActive,cutoff).Find(&calls).Error;e!=nil{log.Printf("stale call cleanup failed: %v",e);return};if len(calls)==0{return};now:=time.Now();for _,call:=range calls{if e:=db.Model(&Call{}).Where("id=? AND status=?",call.ID,callActive).Updates(map[string]any{"status":callEnded,"ended_at":now}).Error;e!=nil{log.Printf("stale call %s cleanup failed: %v",call.ID,e);continue};h.broadcast(call.ConversationID,gin.H{"type":"call_ended","callId":call.ID,"by":"system","endedAt":now,"reason":"expired"})}}

func main(){
 cfg,e:=loadConfig();if e!=nil{log.Fatal(e)};db,e:=gorm.Open(postgres.Open(cfg.DatabaseURL),&gorm.Config{});if e!=nil{log.Fatal(e)};if e=db.AutoMigrate(&Conversation{},&ConversationMember{},&Message{},&ReadReceipt{},&Call{});e!=nil{log.Fatal(e)};if e:=db.Exec("CREATE INDEX IF NOT EXISTS idx_messages_conversation_created_id ON messages (conversation_id, created_at DESC, id DESC)").Error;e!=nil{log.Fatal(e)};if e:=db.Exec("CREATE INDEX IF NOT EXISTS idx_conversations_updated_at ON conversations (updated_at DESC)").Error;e!=nil{log.Fatal(e)};if e:=db.Exec("CREATE UNIQUE INDEX IF NOT EXISTS ux_messages_client_id ON messages (conversation_id, sender_id, client_id) WHERE client_id <> ''").Error;e!=nil{log.Fatalf("message idempotency index migration failed: %v; check for duplicate non-empty client_id rows before retrying",e)};if e:=db.Exec("CREATE INDEX IF NOT EXISTS idx_read_receipts_user_message ON read_receipts (user_id, message_id)").Error;e!=nil{log.Fatal(e)};if e:=db.Exec("CREATE INDEX IF NOT EXISTS idx_conversation_members_user_conversation ON conversation_members (user_id, conversation_id)").Error;e!=nil{log.Fatal(e)};if e:=db.Exec("CREATE INDEX IF NOT EXISTS idx_conversation_members_conversation_user ON conversation_members (conversation_id, user_id)").Error;e!=nil{log.Fatal(e)};if e:=db.Exec("CREATE INDEX IF NOT EXISTS idx_read_receipts_message_user ON read_receipts (message_id, user_id)").Error;e!=nil{log.Fatal(e)};if e:=db.Exec("CREATE UNIQUE INDEX IF NOT EXISTS ux_active_call_conversation ON calls (conversation_id) WHERE status = 'ACTIVE'").Error;e!=nil{log.Fatalf("active call index migration failed: %v; check for multiple ACTIVE calls in the same conversation before retrying",e)}
 h:=newHub();go func(){ticker:=time.NewTicker(5*time.Minute);defer ticker.Stop();for{expireStaleCalls(db,h);<-ticker.C}}();r:=gin.New();r.Use(gin.Logger(),gin.Recovery());if cfg.FrontendURL!=""{co:=cors.DefaultConfig();co.AllowOrigins=[]string{cfg.FrontendURL};co.AllowCredentials=true;co.AllowHeaders=[]string{"Origin","Content-Type","Authorization"};r.Use(cors.New(co))}
 r.GET("/health",func(c *gin.Context){c.JSON(200,gin.H{"status":"ok","service":"message"})});r.GET("/ready",func(c *gin.Context){s,e:=db.DB();if e!=nil||s.Ping()!=nil{c.JSON(503,gin.H{"status":"not_ready"});return};c.JSON(200,gin.H{"status":"ready"})})
 api:=r.Group("/v1",authMW(cfg.JWTSecret))
 api.POST("/conversations",func(c *gin.Context){var in struct{Type string `json:"type"`;Title string `json:"title"`;MemberIDs []string `json:"memberIds"`};if c.BindJSON(&in)!=nil{c.JSON(400,gin.H{"error":"invalid request"});return};if len(in.Title)>160{c.JSON(400,gin.H{"error":"title too long"});return};if in.Type==""{in.Type=conversationDirect};if in.Type!=conversationDirect&&in.Type!=conversationGroup{c.JSON(400,gin.H{"error":"invalid conversation type"});return};members:=map[string]bool{uid(c):true};for _,m:=range in.MemberIDs{m=strings.TrimSpace(m);if m!=""{members[m]=true}};if len(members)>100{c.JSON(400,gin.H{"error":"too many conversation members"});return};if in.Type==conversationDirect&&len(members)!=2{c.JSON(400,gin.H{"error":"direct conversation requires two users"});return};if in.Type==conversationGroup&&len(members)<2{c.JSON(400,gin.H{"error":"group conversation requires at least two users"});return};conv:=Conversation{ID:newID(),Type:in.Type,Title:in.Title,CreatedBy:uid(c)};tx:=db.Begin();if tx.Error!=nil{c.JSON(500,gin.H{"error":"transaction failed"});return};
if in.Type==conversationDirect{
  ids:=make([]string,0,2);for m:=range members{ids=append(ids,m)}
  if len(ids)==2&&ids[0]>ids[1]{ids[0],ids[1]=ids[1],ids[0]}
  lockKey:=ids[0]+":"+ids[1]
  if e:=tx.Exec("SELECT pg_advisory_xact_lock(hashtext(?))",lockKey).Error;e!=nil{tx.Rollback();c.JSON(500,gin.H{"error":"conversation lock failed"});return}
  var existing Conversation
  if e:=tx.Raw("SELECT c.* FROM conversations c JOIN conversation_members m1 ON m1.conversation_id=c.id AND m1.user_id=? JOIN conversation_members m2 ON m2.conversation_id=c.id AND m2.user_id=? WHERE c.type=? AND (SELECT COUNT(*) FROM conversation_members mx WHERE mx.conversation_id=c.id)=2 ORDER BY c.created_at ASC LIMIT 1",ids[0],ids[1],conversationDirect).Scan(&existing).Error;e==nil&&existing.ID!=""{
    tx.Rollback()
    c.JSON(200,existing)
    return
  }
}
if e:=tx.Create(&conv).Error;e!=nil{tx.Rollback();c.JSON(500,gin.H{"error":"create conversation failed"});return};for m:=range members{if e:=tx.Create(&ConversationMember{ConversationID:conv.ID,UserID:m,JoinedAt:time.Now()}).Error;e!=nil{tx.Rollback();c.JSON(500,gin.H{"error":"add member failed"});return}};if e:=tx.Commit().Error;e!=nil{c.JSON(500,gin.H{"error":"commit failed"});return};c.JSON(201,conv)})
 api.GET("/conversations",func(c *gin.Context){var ms []ConversationMember;if e:=db.Where("user_id=?",uid(c)).Find(&ms).Error;e!=nil{c.JSON(500,gin.H{"error":"list failed"});return};ids:=make([]string,0,len(ms));for _,m:=range ms{ids=append(ids,m.ConversationID)};var cs []Conversation;if len(ids)>0{if e:=db.Where("id IN ?",ids).Order("updated_at DESC").Find(&cs).Error;e!=nil{c.JSON(500,gin.H{"error":"list failed"});return}};type conversationView struct{Conversation;MemberIDs []string `json:"memberIds"`;UnreadCount int64 `json:"unreadCount"`};out:=make([]conversationView,0,len(cs));if len(cs)>0{memberRows:=make([]ConversationMember,0);if e:=db.Where("conversation_id IN ?",ids).Find(&memberRows).Error;e!=nil{c.JSON(500,gin.H{"error":"list members failed"});return};memberMap:=map[string][]string{};for _,m:=range memberRows{memberMap[m.ConversationID]=append(memberMap[m.ConversationID],m.UserID)};unreadRows:=make([]struct{ConversationID string `gorm:"column:conversation_id"`;Count int64 `gorm:"column:count"`},0);if e:=db.Raw("SELECT m.conversation_id, COUNT(*) AS count FROM messages m WHERE m.conversation_id IN ? AND m.sender_id <> ? AND NOT EXISTS (SELECT 1 FROM read_receipts r WHERE r.message_id=m.id AND r.user_id=?) GROUP BY m.conversation_id",ids,uid(c),uid(c)).Scan(&unreadRows).Error;e!=nil{c.JSON(500,gin.H{"error":"unread count failed"});return};unreadMap:=map[string]int64{};for _,row:=range unreadRows{unreadMap[row.ConversationID]=row.Count};for _,conv:=range cs{out=append(out,conversationView{Conversation:conv,MemberIDs:memberMap[conv.ID],UnreadCount:unreadMap[conv.ID]})}};c.JSON(200,out)})
 api.GET("/conversations/:id/messages",func(c *gin.Context){id:=c.Param("id");if !requireMember(db,c,id){return};limit,_:=strconv.Atoi(c.DefaultQuery("limit","50"));if limit<1||limit>100{limit=50};before:=strings.TrimSpace(c.Query("before"));var ms []Message;q:=db.Where("conversation_id=?",id);if before!=""{var cursor Message;if db.Where("id=? AND conversation_id=?",before,id).First(&cursor).Error!=nil{c.JSON(400,gin.H{"error":"invalid cursor"});return};q=q.Where("(created_at < ?) OR (created_at = ? AND id < ?)",cursor.CreatedAt,cursor.CreatedAt,cursor.ID)};if e:=q.Order("created_at DESC,id DESC").Limit(limit+1).Find(&ms).Error;e!=nil{c.JSON(500,gin.H{"error":"history failed"});return};hasMore:=len(ms)>limit;if hasMore{ms=ms[:limit]};for i,j:=0,len(ms)-1;i<j;i,j=i+1,j-1{ms[i],ms[j]=ms[j],ms[i]};nextBefore:="";if hasMore&&len(ms)>0{nextBefore=ms[0].ID};c.JSON(200,gin.H{"messages":ms,"nextBefore":nextBefore,"hasMore":hasMore})})
 api.GET("/conversations/:id/unread",func(c *gin.Context){id:=c.Param("id");if !requireMember(db,c,id){return};var n int64;if e:=db.Raw("SELECT COUNT(*) FROM messages m WHERE m.conversation_id = ? AND m.sender_id <> ? AND NOT EXISTS (SELECT 1 FROM read_receipts r WHERE r.message_id=m.id AND r.user_id=?)",id,uid(c),uid(c)).Scan(&n).Error;e!=nil{c.JSON(500,gin.H{"error":"unread count failed"});return};c.JSON(200,gin.H{"count":n})})
 api.POST("/conversations/:id/read-through",func(c *gin.Context){id:=c.Param("id");if !requireMember(db,c,id){return};var in struct{MessageID string `json:"messageId"`};if c.BindJSON(&in)!=nil||in.MessageID==""{c.JSON(400,gin.H{"error":"messageId required"});return};var target Message;if db.Where("id=? AND conversation_id=?",in.MessageID,id).First(&target).Error!=nil{c.JSON(404,gin.H{"error":"message not found"});return};if target.SenderID==uid(c){c.JSON(400,gin.H{"error":"cannot mark own message as read"});return};now:=time.Now();if e:=db.Exec(`INSERT INTO read_receipts (message_id,user_id,read_at) SELECT m.id,?,? FROM messages m WHERE m.conversation_id=? AND m.sender_id<>? AND (m.created_at < ? OR (m.created_at = ? AND m.id <= ?)) ON CONFLICT (message_id,user_id) DO UPDATE SET read_at=EXCLUDED.read_at`,uid(c),now,id,uid(c),target.CreatedAt,target.CreatedAt,target.ID).Error;e!=nil{c.JSON(500,gin.H{"error":"mark read failed"});return};h.broadcast(id,gin.H{"type":"read_through","messageId":target.ID,"userId":uid(c),"readAt":now});c.JSON(200,gin.H{"ok":true});return});api.POST("/conversations/:id/read",func(c *gin.Context){id:=c.Param("id");if !requireMember(db,c,id){return};var in struct{MessageID string `json:"messageId"`};if c.BindJSON(&in)!=nil||in.MessageID==""{c.JSON(400,gin.H{"error":"messageId required"});return};var m Message;if db.Where("id=? AND conversation_id=?",in.MessageID,id).First(&m).Error!=nil{c.JSON(404,gin.H{"error":"message not found"});return};if m.SenderID==uid(c){c.JSON(400,gin.H{"error":"cannot mark own message as read"});return};now:=time.Now();if e:=db.Where("message_id=? AND user_id=?",in.MessageID,uid(c)).Assign(ReadReceipt{MessageID:in.MessageID,UserID:uid(c),ReadAt:now}).FirstOrCreate(&ReadReceipt{}).Error;e!=nil{c.JSON(500,gin.H{"error":"mark read failed"});return};h.broadcast(id,gin.H{"type":"read","messageId":in.MessageID,"userId":uid(c),"readAt":now});c.JSON(200,gin.H{"ok":true})})
 api.POST("/conversations/:id/calls",func(c *gin.Context){id:=c.Param("id");if !requireMember(db,c,id){return};if cfg.LiveKitURL==""||cfg.LiveKitKey==""||cfg.LiveKitSecret==""{c.JSON(503,gin.H{"error":"live calls are not configured"});return};var active Call;if db.Where("conversation_id=? AND status=?",id,callActive).First(&active).Error==nil{c.JSON(409,gin.H{"error":"an active call already exists","call":active});return};call:=Call{ID:newID(),ConversationID:id,RoomName:"notell-call-"+newID(),CreatedBy:uid(c),Status:callActive,CreatedAt:time.Now()};if e:=db.Create(&call).Error;e!=nil{var existing Call;if db.Where("conversation_id=? AND status=?",id,callActive).First(&existing).Error==nil{c.JSON(409,gin.H{"error":"an active call already exists","call":existing});return};c.JSON(500,gin.H{"error":"create call failed"});return};t,e:=callToken(cfg.LiveKitKey,cfg.LiveKitSecret,call.RoomName,uid(c));if e!=nil{now:=time.Now();_=db.Model(&call).Updates(map[string]any{"status":callEnded,"ended_at":now});c.JSON(500,gin.H{"error":"create call token failed"});return};h.broadcast(id,gin.H{"type":"call_invite","callId":call.ID,"roomName":call.RoomName,"from":uid(c)});c.JSON(201,gin.H{"call":call,"wsUrl":cfg.LiveKitURL,"token":t})})
 api.POST("/calls/:id/token",func(c *gin.Context){var call Call;if db.First(&call,"id=?",c.Param("id")).Error!=nil{c.JSON(404,gin.H{"error":"call not found"});return};if call.Status!="ACTIVE"{c.JSON(409,gin.H{"error":"call has ended"});return};if !member(db,call.ConversationID,uid(c)){c.JSON(403,gin.H{"error":"conversation membership required"});return};if cfg.LiveKitURL==""||cfg.LiveKitKey==""||cfg.LiveKitSecret==""{c.JSON(503,gin.H{"error":"live calls are not configured"});return};t,e:=callToken(cfg.LiveKitKey,cfg.LiveKitSecret,call.RoomName,uid(c));if e!=nil{c.JSON(500,gin.H{"error":"token failed"});return};c.JSON(200,gin.H{"wsUrl":cfg.LiveKitURL,"token":t,"roomName":call.RoomName})})
 api.POST("/calls/:id/end",func(c *gin.Context){var call Call;if db.First(&call,"id=?",c.Param("id")).Error!=nil{c.JSON(404,gin.H{"error":"call not found"});return};if call.CreatedBy!=uid(c){c.JSON(403,gin.H{"error":"call owner required"});return};if call.Status=="ENDED"{c.JSON(200,call);return};now:=time.Now();if e:=db.Model(&call).Updates(map[string]any{"status":"ENDED","ended_at":now}).Error;e!=nil{c.JSON(500,gin.H{"error":"end call failed"});return};call.Status="ENDED";call.EndedAt=&now;h.broadcast(call.ConversationID,gin.H{"type":"call_ended","callId":call.ID,"by":uid(c),"endedAt":now});c.JSON(200,call)})
 api.GET("/ws/:conversationId",func(c *gin.Context){conv:=c.Param("conversationId");user,ok:=userIDFromJWT(c,cfg.JWTSecret);if !ok||!member(db,conv,user){c.JSON(403,gin.H{"error":"conversation membership required"});return};origin:=c.GetHeader("Origin");if cfg.FrontendURL!=""&&origin!=""&&origin!=cfg.FrontendURL{c.JSON(403,gin.H{"error":"origin not allowed"});return};up:=websocket.Upgrader{ReadBufferSize:4096,WriteBufferSize:4096,CheckOrigin:func(r *http.Request)bool{return cfg.FrontendURL==""||r.Header.Get("Origin")==""||r.Header.Get("Origin")==cfg.FrontendURL}};ws,e:=up.Upgrade(c.Writer,c.Request,nil);if e!=nil{return};ws.SetReadLimit(1<<20);_=ws.SetReadDeadline(time.Now().Add(75*time.Second));ws.SetPongHandler(func(string)error{return ws.SetReadDeadline(time.Now().Add(75*time.Second))});safe:=&safeSocket{conn:ws};h.add(conv,safe);pingDone:=make(chan struct{});defer close(pingDone);go func(){ticker:=time.NewTicker(30*time.Second);defer ticker.Stop();for{select{case <-ticker.C:if safe.ping()!=nil{return};case <-pingDone:return}}}();defer func(){h.remove(conv,safe);_ = ws.Close()}();_=safe.write(gin.H{"type":"connected","conversationId":conv,"userId":user});
  for{var in struct{Type string `json:"type"`;Body string `json:"body"`;ClientID string `json:"clientId"`;MessageID string `json:"messageId"`};if e=ws.ReadJSON(&in);e!=nil{return};_=ws.SetReadDeadline(time.Now().Add(75*time.Second));switch in.Type{case "message":if strings.TrimSpace(in.Body)==""||len(in.Body)>10000||len(in.ClientID)>64{_=safe.write(gin.H{"type":"error","error":"invalid message body","clientId":in.ClientID});continue};var m Message;duplicate:=false;if in.ClientID!=""{if db.Where("conversation_id=? AND sender_id=? AND client_id=?",conv,user,in.ClientID).First(&m).Error==nil{duplicate=true}};if !duplicate{m=Message{ID:newID(),ConversationID:conv,SenderID:user,Type:messageTypeText,Body:in.Body,ClientID:in.ClientID,CreatedAt:time.Now()};if e=db.Create(&m).Error;e!=nil{if in.ClientID!=""&&db.Where("conversation_id=? AND sender_id=? AND client_id=?",conv,user,in.ClientID).First(&m).Error==nil{duplicate=true}else{_=safe.write(gin.H{"type":"error","error":"message persistence failed","clientId":in.ClientID});continue}}};if !duplicate{if e:=db.Model(&Conversation{}).Where("id=?",conv).Update("updated_at",m.CreatedAt).Error;e!=nil{_=safe.write(gin.H{"type":"error","error":"conversation timestamp update failed","clientId":in.ClientID})}};h.broadcast(conv,gin.H{"type":"message","message":m,"duplicate":duplicate});case "typing":h.broadcast(conv,gin.H{"type":"typing","userId":user,"typing":true,"expiresInMs":4000});case "stop_typing":h.broadcast(conv,gin.H{"type":"typing","userId":user,"typing":false});case "read":if in.MessageID!=""{var m Message;if db.Where("id=? AND conversation_id=?",in.MessageID,conv).First(&m).Error==nil{now:=time.Now();if e:=db.Where("message_id=? AND user_id=?",in.MessageID,user).Assign(ReadReceipt{MessageID:in.MessageID,UserID:user,ReadAt:now}).FirstOrCreate(&ReadReceipt{}).Error;e!=nil{_=safe.write(gin.H{"type":"error","error":"mark read failed","messageId":in.MessageID});continue};h.broadcast(conv,gin.H{"type":"read","messageId":in.MessageID,"userId":user,"readAt":now})}}}}
 })
 log.Printf("message service listening on :%s",cfg.Port);log.Fatal(r.Run(":"+cfg.Port))
}
